Stride Reference Manual: geopop::GeoGridJSONWriter Class Reference
geopop::GeoGridJSONWriter Class Reference
Writes a GeoGrid to a JSON file.
#include <GeoGridJSONWriter.h>
Public Member Functions
GeoGridJSONWriter ()=delete
GeoGridJSONWriter cannot be instantiated without stream.
GeoGridJSONWriter (std::shared_ptr< std::ostream > stream)
Construct GeoGridProtoWriter referencing given stream.
void Write (GeoGrid< Epidemiologic > &geoGrid) override
Write the provided GeoGrid to the proved ostream in JSON format.
Public Member Functions inherited from geopop::GeoGridStreamWriter
GeoGridStreamWriter ()=delete
GeoGridStreamWriter cannot be instantiated without stream.
GeoGridStreamWriter (std::shared_ptr< std::ostream > stream)
Construct GeoGridStreamWriter referencing given stream.
~GeoGridStreamWriter () override=default
Default destructor.
std::shared_ptr< std::ostream > StreamRef ()
Return reference to output stream.
Public Member Functions inherited from geopop::GeoGridWriter
GeoGridWriter ()=default
Default construtor.
virtual ~GeoGridWriter ()=default
Virtual destrutor to make class abstract.
Private Member Functions
nlohmann::json WriteContactPool (const stride::ContactPool *contactPool)
Create a JSON object containing all info needed to reconstruct a ContactPool.
nlohmann::json WriteCoordinate (const Coordinate &coordinate)
Create a JSON object containing all info needed to reconstruct a Coordinate.
nlohmann::json WriteLocation (const Location< Epidemiologic > &location)
Create a JSON object containing all info needed to reconstruct a Location.
nlohmann::json WritePerson (stride::Person *person)
Create a JSON object containing all info needed to reconstruct a Person.
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
Additional Inherited Members
Protected Attributes inherited from geopop::GeoGridStreamWriter
std::shared_ptr< std::ostream > m_stream
Detailed Description
Writes a GeoGrid to a JSON file.
Definition at line 36 of file GeoGridJSONWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridJSONWriter::GeoGridJSONWriter () delete
GeoGridJSONWriter cannot be instantiated without stream.
geopop::GeoGridJSONWriter::GeoGridJSONWriter (std::shared_ptr< std::ostream > stream) explicit
Construct GeoGridProtoWriter referencing given stream.
Member Function Documentation
void geopop::GeoGridJSONWriter::Write (GeoGrid< Epidemiologic > & geoGrid) override virtual
Write the provided GeoGrid to the proved ostream in JSON format.
Implements geopop::GeoGridStreamWriter.
Definition at line 36 of file GeoGridJSONWriter.cpp.
nlohmann::json geopop::GeoGridJSONWriter::WriteContactPool (const stride::ContactPool * contactPool) private
Create a JSON object containing all info needed to reconstruct a ContactPool.
Definition at line 97 of file GeoGridJSONWriter.cpp.
References stride::ContactPool::GetId(), and stride::ContactPool::GetPool().
nlohmann::json geopop::GeoGridJSONWriter::WriteCoordinate (const Coordinate & coordinate) private
Create a JSON object containing all info needed to reconstruct a Coordinate.
Definition at line 87 of file GeoGridJSONWriter.cpp.
nlohmann::json geopop::GeoGridJSONWriter::WriteLocation (const Location< Epidemiologic > & location) private
Create a JSON object containing all info needed to reconstruct a Location.
Definition at line 53 of file GeoGridJSONWriter.cpp.
References geopop::Location< Content >::GetContent(), geopop::Location< Content >::GetCoordinate(), geopop::Location< Content >::GetID(), geopop::Location< Content >::GetName(), geopop::Location< Content >::GetProvince(), stride::ContactType::IdList, and stride::ContactLogMode::ToString().
nlohmann::json geopop::GeoGridJSONWriter::WritePerson (stride::Person * person) private
Create a JSON object containing all info needed to reconstruct a Person.
Definition at line 112 of file GeoGridJSONWriter.cpp.
References stride::Person::GetAge(), stride::Person::GetId(), and stride::Person::GetPoolId().
Member Data Documentation
std::set<stride::Person*> geopop::GeoGridJSONWriter::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 62 of file GeoGridJSONWriter.h.
The documentation for this class was generated from the following files:
GeoGridJSONWriter.h
GeoGridJSONWriter.cpp