Stride Reference Manual: proto::EpiOutput_Day Class Reference
proto::EpiOutput_Day Class Reference final
#include <epioutput.pb.h>
Public Types
typedef EpiOutput_Day_Location Location
Public Member Functions
EpiOutput_Day ()
virtual ~EpiOutput_Day ()
EpiOutput_Day (const EpiOutput_Day &from)
EpiOutput_Day & operator= (const EpiOutput_Day &from)
void Swap (EpiOutput_Day *other)
EpiOutput_Day * New () const final
EpiOutput_Day * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const EpiOutput_Day &from)
void MergeFrom (const EpiOutput_Day &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int locations_size () const
void clear_locations ()
::proto::EpiOutput_Day_Location * mutable_locations (int index)
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location > * mutable_locations ()
const ::proto::EpiOutput_Day_Location & locations (int index) const
::proto::EpiOutput_Day_Location * add_locations ()
const ::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location > & locations () const
void clear_day ()
::google::protobuf::int64 day () const
void set_day (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const EpiOutput_Day & default_instance ()
static void InitAsDefaultInstance ()
static const EpiOutput_Day * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kLocationsFieldNumber = 2
static const int kDayFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (EpiOutput_Day *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location > locations_
::google::protobuf::int64 day_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_epioutput_2eproto
void swap (EpiOutput_Day &a, EpiOutput_Day &b)
Detailed Description
Definition at line 633 of file epioutput.pb.h.
Member Typedef Documentation
typedef EpiOutput_Day_Location proto::EpiOutput_Day::Location
Definition at line 726 of file epioutput.pb.h.
Constructor & Destructor Documentation
proto::EpiOutput_Day::EpiOutput_Day ()
virtual proto::EpiOutput_Day::~EpiOutput_Day () virtual
proto::EpiOutput_Day::EpiOutput_Day (const EpiOutput_Day & from)
Member Function Documentation
EpiOutput_Day& proto::EpiOutput_Day::operator= (const EpiOutput_Day & from) inline
Definition at line 641 of file epioutput.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::EpiOutput_Day::descriptor () inline static
Definition at line 660 of file epioutput.pb.h.
static const EpiOutput_Day& proto::EpiOutput_Day::default_instance () static
static void proto::EpiOutput_Day::InitAsDefaultInstance () static
static const EpiOutput_Day* proto::EpiOutput_Day::internal_default_instance () inline static
Definition at line 666 of file epioutput.pb.h.
References proto::_EpiOutput_Day_default_instance_.
void proto::EpiOutput_Day::Swap (EpiOutput_Day * other)
EpiOutput_Day* proto::EpiOutput_Day::New () const inline final
Definition at line 680 of file epioutput.pb.h.
EpiOutput_Day* proto::EpiOutput_Day::New (::google::protobuf::Arena * arena) const inline final
Definition at line 684 of file epioutput.pb.h.
void proto::EpiOutput_Day::CopyFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day::MergeFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day::CopyFrom (const EpiOutput_Day & from)
void proto::EpiOutput_Day::MergeFrom (const EpiOutput_Day & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::EpiOutput_Day::Clear () final
bool proto::EpiOutput_Day::IsInitialized () const final
size_t proto::EpiOutput_Day::ByteSizeLong () const final
bool proto::EpiOutput_Day::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::EpiOutput_Day::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::EpiOutput_Day::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::EpiOutput_Day::GetCachedSize () const inline final
Definition at line 706 of file epioutput.pb.h.
void proto::EpiOutput_Day::SharedCtor () private
void proto::EpiOutput_Day::SharedDtor () private
void proto::EpiOutput_Day::SetCachedSize (int size) const final private
void proto::EpiOutput_Day::InternalSwap (EpiOutput_Day * other) private
inline ::google::protobuf::Arena* proto::EpiOutput_Day::GetArenaNoVirtual () const inline private
Definition at line 714 of file epioutput.pb.h.
Referenced by operator=().
void* proto::EpiOutput_Day::MaybeArenaPtr () const inline private
Definition at line 717 of file epioutput.pb.h.
::google::protobuf::Metadata proto::EpiOutput_Day::GetMetadata () const final
int proto::EpiOutput_Day::locations_size () const inline
Definition at line 1274 of file epioutput.pb.h.
void proto::EpiOutput_Day::clear_locations () inline
Definition at line 1277 of file epioutput.pb.h.
proto::EpiOutput_Day_Location * proto::EpiOutput_Day::mutable_locations (int index) inline
Definition at line 1280 of file epioutput.pb.h.
google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day_Location > * proto::EpiOutput_Day::mutable_locations () inline
Definition at line 1285 of file epioutput.pb.h.
const ::proto::EpiOutput_Day_Location & proto::EpiOutput_Day::locations (int index) const inline
Definition at line 1289 of file epioutput.pb.h.
Referenced by visualization::EpiOutputProtoReader::Read().
proto::EpiOutput_Day_Location * proto::EpiOutput_Day::add_locations () inline
Definition at line 1293 of file epioutput.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day_Location > & proto::EpiOutput_Day::locations () const inline
Definition at line 1298 of file epioutput.pb.h.
void proto::EpiOutput_Day::clear_day () inline
Definition at line 1260 of file epioutput.pb.h.
google::protobuf::int64 proto::EpiOutput_Day::day () const inline
Definition at line 1263 of file epioutput.pb.h.
void proto::EpiOutput_Day::set_day (::google::protobuf::int64 value) inline
Definition at line 1267 of file epioutput.pb.h.
Referenced by geopop::EpiOutputProtoWriter::Update().
Friends And Related Function Documentation
friend struct ::TableStruct_epioutput_2eproto friend
Definition at line 756 of file epioutput.pb.h.
void swap (EpiOutput_Day & a, EpiOutput_Day & b) friend
Definition at line 674 of file epioutput.pb.h.
Member Data Documentation
constexpr int proto::EpiOutput_Day::kIndexInFileMessages static
Initial value:
=
    4
Definition at line 670 of file epioutput.pb.h.
const int proto::EpiOutput_Day::kLocationsFieldNumber = 2 static
Definition at line 733 of file epioutput.pb.h.
const int proto::EpiOutput_Day::kDayFieldNumber = 1 static
Definition at line 744 of file epioutput.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::EpiOutput_Day::_internal_metadata_ private
Definition at line 750 of file epioutput.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location > proto::EpiOutput_Day::locations_ private
Definition at line 753 of file epioutput.pb.h.
::google::protobuf::int64 proto::EpiOutput_Day::day_ private
Definition at line 754 of file epioutput.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::EpiOutput_Day::_cached_size_ private
Definition at line 755 of file epioutput.pb.h.
The documentation for this class was generated from the following file:
epioutput.pb.h