Stride Reference Manual: geopop::GeoGridStreamWriter Class Reference
geopop::GeoGridStreamWriter Class Reference abstract
An interface for writing the GeoGrid to an output stream, can be implemented with multiple file types.
#include <GeoGridStreamWriter.h>
Public Member Functions
GeoGridStreamWriter ()=delete
GeoGridStreamWriter cannot be instantiated without stream.
GeoGridStreamWriter (std::shared_ptr< std::ostream > stream)
Construct GeoGridStreamWriter referencing given stream.
~GeoGridStreamWriter () override=default
Default destructor.
void Write (GeoGrid< Epidemiologic > &geoGrid) override=0
Write the GeoGrid to ostream.
std::shared_ptr< std::ostream > StreamRef ()
Return reference to output stream.
Public Member Functions inherited from geopop::GeoGridWriter
GeoGridWriter ()=default
Default construtor.
virtual ~GeoGridWriter ()=default
Virtual destrutor to make class abstract.
Protected Attributes
std::shared_ptr< std::ostream > m_stream
Detailed Description
An interface for writing the GeoGrid to an output stream, can be implemented with multiple file types.
Protobuf and json are currently implemented.
Definition at line 32 of file GeoGridStreamWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridStreamWriter::GeoGridStreamWriter () delete
GeoGridStreamWriter cannot be instantiated without stream.
geopop::GeoGridStreamWriter::GeoGridStreamWriter (std::shared_ptr< std::ostream > stream) inline explicit
Construct GeoGridStreamWriter referencing given stream.
Definition at line 39 of file GeoGridStreamWriter.h.
References Write(), and ~GeoGridStreamWriter().
geopop::GeoGridStreamWriter::~GeoGridStreamWriter () override default
Default destructor.
Referenced by GeoGridStreamWriter().
Member Function Documentation
void geopop::GeoGridStreamWriter::Write (GeoGrid< Epidemiologic > & geoGrid) override pure virtual
Write the GeoGrid to ostream.
Implements geopop::GeoGridWriter.
Implemented in geopop::GeoGridProtoWriter, and geopop::GeoGridJSONWriter.
Referenced by GeoGridStreamWriter().
std::shared_ptr<std::ostream> geopop::GeoGridStreamWriter::StreamRef () inline
Return reference to output stream.
Definition at line 48 of file GeoGridStreamWriter.h.
References m_stream.
Member Data Documentation
std::shared_ptr<std::ostream> geopop::GeoGridStreamWriter::m_stream protected
Definition at line 51 of file GeoGridStreamWriter.h.
Referenced by StreamRef().
The documentation for this class was generated from the following file:
GeoGridStreamWriter.h