Stride Reference Manual: stride::ContactPool Class Reference
stride::ContactPool Class Reference
A group of Persons that potentially have contacts with one another.
#include <ContactPool.h>
Public Types
using iterator = std::vector< stride::Person * >::iterator
Public Member Functions
ContactPool (unsigned int poolId, ContactType::Id type, unsigned int limit=std::numeric_limits< unsigned int >::infinity())
Initializing constructor.
~ContactPool ()=default
Default will do.
void AddMember (Person *p)
Add the given Person.
bool CheckLimit ()
Check if pool has reached its Limit.
unsigned int GetLimit () const
Get the pool limit.
unsigned int GetId () const
Get the pool id.
unsigned int GetInfectedCount () const
Get Infected count.
const std::vector< Person * > & GetPool () const
Get the entire pool of members.
ContactType::Id GetType () const
Get the type of ContactPool, used for logging and tests.
std::map< std::string, std::map< std::string, unsigned int > > const GenerateEpiOutput ()
Generate an epi-output map of the contactpool.
iterator begin ()
Iterator to first person.
iterator end ()
Iterator to end of persons.
size_t size () const
Gets current size of Location storage.
Person *const & operator[] (size_t index) const
Gets a Person by index, doesn't performs a range check.
Private Member Functions
std::tuple< bool, unsigned int > SortMembers ()
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Private Attributes
unsigned int m_index_immune
Index of the first immune member in the ContactPool.
unsigned int m_pool_id
The ID of the ContactPool (for logging purposes).
ContactType::Id m_pool_type
The type of the ContactPool (for logging and testing purposes).
std::vector< Person * > m_members
Pointers to contactpool members (raw pointers intentional).
unsigned int m_limit
Limit for the number of contactpool members (distribution purposes).
Friends
template<ContactLogMode::Id LL, bool TIC, bool TO>
class Infector
Calculates contacts and transmissions; accesses private methods and data.
Detailed Description
A group of Persons that potentially have contacts with one another.
We do not expose the vector that stores pool members because adding & sorting it takes some care.
Definition at line 41 of file ContactPool.h.
Member Typedef Documentation
using stride::ContactPool::iterator = std::vector<stride::Person*>::iterator
Definition at line 76 of file ContactPool.h.
Constructor & Destructor Documentation
stride::ContactPool::ContactPool (unsigned int poolId, ContactType::Id type, unsigned int limit = std::numeric_limits<unsigned int>::infinity())
Initializing constructor.
Definition at line 34 of file ContactPool.cpp.
stride::ContactPool::~ContactPool () default
Default will do.
Member Function Documentation
void stride::ContactPool::AddMember (Person * p)
Add the given Person.
Definition at line 39 of file ContactPool.cpp.
References m_index_immune, and m_members.
bool stride::ContactPool::CheckLimit ()
Check if pool has reached its Limit.
Definition at line 45 of file ContactPool.cpp.
References m_limit, and m_members.
unsigned int stride::ContactPool::GetLimit () const inline
Get the pool limit.
Definition at line 57 of file ContactPool.h.
References m_limit.
unsigned int stride::ContactPool::GetId () const inline
Get the pool id.
Definition at line 60 of file ContactPool.h.
References GetInfectedCount(), and m_pool_id.
Referenced by geopop::GeoGridJSONWriter::WriteContactPool(), geopop::GeoGridHDF5Writer::WriteContactPool(), and geopop::GeoGridProtoWriter::WriteContactPool().
unsigned int stride::ContactPool::GetInfectedCount () const
Get Infected count.
Definition at line 53 of file ContactPool.cpp.
References m_members.
Referenced by GetId().
const std::vector<Person*>& stride::ContactPool::GetPool () const inline
Get the entire pool of members.
Definition at line 66 of file ContactPool.h.
References m_members.
Referenced by stride::Immunizer::Random(), and geopop::GeoGridJSONWriter::WriteContactPool().
ContactType::Id stride::ContactPool::GetType () const inline
Get the type of ContactPool, used for logging and tests.
Definition at line 69 of file ContactPool.h.
References GenerateEpiOutput(), and m_pool_type.
const std::map< std::string, std::map< std::string, unsigned int > > stride::ContactPool::GenerateEpiOutput ()
Generate an epi-output map of the contactpool.
Definition at line 65 of file ContactPool.cpp.
References stride::ageBrackets, stride::AgeBrackets::Daycare::HasAge(), stride::AgeBrackets::PreSchool::HasAge(), stride::AgeBrackets::K12School::HasAge(), stride::AgeBrackets::College::HasAge(), stride::AgeBrackets::Workplace::HasAge(), stride::healthStatuses, m_members, and stride::ContactType::Workplace.
Referenced by GetType().
iterator stride::ContactPool::begin () inline
Iterator to first person.
Definition at line 79 of file ContactPool.h.
References m_members.
iterator stride::ContactPool::end () inline
Iterator to end of persons.
Definition at line 82 of file ContactPool.h.
References m_members.
size_t stride::ContactPool::size () const inline
Gets current size of Location storage.
Definition at line 85 of file ContactPool.h.
References m_members.
Referenced by geopop::GeoGridHDF5Writer::WriteContactPool().
Person* const& stride::ContactPool::operator[] (size_t index) const inline
Gets a Person by index, doesn't performs a range check.
Definition at line 88 of file ContactPool.h.
References m_members, and SortMembers().
std::tuple< bool, unsigned int > stride::ContactPool::SortMembers () private
Sort w.r.t. health status: order: exposed/infected/recovered, susceptible, immune.
Definition at line 117 of file ContactPool.cpp.
References m_index_immune, and m_members.
Referenced by stride::Infector< LL, TIC, true >::Exec(), and operator[]().
Friends And Related Function Documentation
template<ContactLogMode::Id LL, bool TIC, bool TO> friend class Infector friend
Calculates contacts and transmissions; accesses private methods and data.
Definition at line 96 of file ContactPool.h.
Member Data Documentation
unsigned int stride::ContactPool::m_index_immune private
Index of the first immune member in the ContactPool.
Definition at line 99 of file ContactPool.h.
Referenced by AddMember(), stride::Infector< LL, TIC, true >::Exec(), and SortMembers().
unsigned int stride::ContactPool::m_pool_id private
The ID of the ContactPool (for logging purposes).
Definition at line 100 of file ContactPool.h.
Referenced by GetId().
ContactType::Id stride::ContactPool::m_pool_type private
The type of the ContactPool (for logging and testing purposes).
Definition at line 101 of file ContactPool.h.
Referenced by stride::Infector< LL, TIC, TO >::Exec(), stride::Infector< LL, TIC, true >::Exec(), and GetType().
std::vector<Person*> stride::ContactPool::m_members private
Pointers to contactpool members (raw pointers intentional).
Definition at line 102 of file ContactPool.h.
Referenced by AddMember(), begin(), CheckLimit(), end(), stride::Infector< LL, TIC, TO >::Exec(), stride::Infector< LL, TIC, true >::Exec(), GenerateEpiOutput(), GetInfectedCount(), GetPool(), operator[](), size(), and SortMembers().
unsigned int stride::ContactPool::m_limit private
Limit for the number of contactpool members (distribution purposes).
Definition at line 103 of file ContactPool.h.
Referenced by CheckLimit(), and GetLimit().
The documentation for this class was generated from the following files:
ContactPool.h
ContactPool.cpp