Stride Reference Manual: proto::EpiOutput_Day_Location Class Reference
proto::EpiOutput_Day_Location Class Reference final
#include <epioutput.pb.h>
Public Types
typedef EpiOutput_Day_Location_Coordinate Coordinate
typedef EpiOutput_Day_Location_AgeBracket AgeBracket
Public Member Functions
EpiOutput_Day_Location ()
virtual ~EpiOutput_Day_Location ()
EpiOutput_Day_Location (const EpiOutput_Day_Location &from)
EpiOutput_Day_Location & operator= (const EpiOutput_Day_Location &from)
void Swap (EpiOutput_Day_Location *other)
EpiOutput_Day_Location * New () const final
EpiOutput_Day_Location * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const EpiOutput_Day_Location &from)
void MergeFrom (const EpiOutput_Day_Location &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int agebrackets_size () const
void clear_agebrackets ()
::proto::EpiOutput_Day_Location_AgeBracket * mutable_agebrackets (int index)
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location_AgeBracket > * mutable_agebrackets ()
const ::proto::EpiOutput_Day_Location_AgeBracket & agebrackets (int index) const
::proto::EpiOutput_Day_Location_AgeBracket * add_agebrackets ()
const ::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location_AgeBracket > & agebrackets () const
void clear_name ()
const ::std::string & name () const
void set_name (const ::std::string &value)
void set_name (const char *value)
void set_name (const char *value, size_t size)
::std::string * mutable_name ()
::std::string * release_name ()
void set_allocated_name (::std::string *name)
bool has_coordinate () const
void clear_coordinate ()
const ::proto::EpiOutput_Day_Location_Coordinate & coordinate () const
::proto::EpiOutput_Day_Location_Coordinate * release_coordinate ()
::proto::EpiOutput_Day_Location_Coordinate * mutable_coordinate ()
void set_allocated_coordinate (::proto::EpiOutput_Day_Location_Coordinate *coordinate)
void clear_id ()
::google::protobuf::int64 id () const
void set_id (::google::protobuf::int64 value)
void clear_province ()
::google::protobuf::int64 province () const
void set_province (::google::protobuf::int64 value)
void clear_population ()
::google::protobuf::int64 population () const
void set_population (::google::protobuf::int64 value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const EpiOutput_Day_Location & default_instance ()
static void InitAsDefaultInstance ()
static const EpiOutput_Day_Location * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kAgeBracketsFieldNumber = 6
static const int kNameFieldNumber = 2
static const int kCoordinateFieldNumber = 5
static const int kIdFieldNumber = 1
static const int kProvinceFieldNumber = 3
static const int kPopulationFieldNumber = 4
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (EpiOutput_Day_Location *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location_AgeBracket > agebrackets_
::google::protobuf::internal::ArenaStringPtr name_
::proto::EpiOutput_Day_Location_Coordinate * coordinate_
::google::protobuf::int64 id_
::google::protobuf::int64 province_
::google::protobuf::int64 population_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_epioutput_2eproto
void swap (EpiOutput_Day_Location &a, EpiOutput_Day_Location &b)
Detailed Description
Definition at line 466 of file epioutput.pb.h.
Member Typedef Documentation
typedef EpiOutput_Day_Location_Coordinate proto::EpiOutput_Day_Location::Coordinate
Definition at line 559 of file epioutput.pb.h.
typedef EpiOutput_Day_Location_AgeBracket proto::EpiOutput_Day_Location::AgeBracket
Definition at line 560 of file epioutput.pb.h.
Constructor & Destructor Documentation
proto::EpiOutput_Day_Location::EpiOutput_Day_Location ()
virtual proto::EpiOutput_Day_Location::~EpiOutput_Day_Location () virtual
proto::EpiOutput_Day_Location::EpiOutput_Day_Location (const EpiOutput_Day_Location & from)
Member Function Documentation
EpiOutput_Day_Location& proto::EpiOutput_Day_Location::operator= (const EpiOutput_Day_Location & from) inline
Definition at line 474 of file epioutput.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::EpiOutput_Day_Location::descriptor () inline static
Definition at line 493 of file epioutput.pb.h.
static const EpiOutput_Day_Location& proto::EpiOutput_Day_Location::default_instance () static
static void proto::EpiOutput_Day_Location::InitAsDefaultInstance () static
static const EpiOutput_Day_Location* proto::EpiOutput_Day_Location::internal_default_instance () inline static
Definition at line 499 of file epioutput.pb.h.
References proto::_EpiOutput_Day_Location_default_instance_.
void proto::EpiOutput_Day_Location::Swap (EpiOutput_Day_Location * other)
EpiOutput_Day_Location* proto::EpiOutput_Day_Location::New () const inline final
Definition at line 513 of file epioutput.pb.h.
EpiOutput_Day_Location* proto::EpiOutput_Day_Location::New (::google::protobuf::Arena * arena) const inline final
Definition at line 517 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::CopyFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day_Location::MergeFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day_Location::CopyFrom (const EpiOutput_Day_Location & from)
void proto::EpiOutput_Day_Location::MergeFrom (const EpiOutput_Day_Location & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::EpiOutput_Day_Location::Clear () final
bool proto::EpiOutput_Day_Location::IsInitialized () const final
size_t proto::EpiOutput_Day_Location::ByteSizeLong () const final
bool proto::EpiOutput_Day_Location::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::EpiOutput_Day_Location::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::EpiOutput_Day_Location::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::EpiOutput_Day_Location::GetCachedSize () const inline final
Definition at line 539 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::SharedCtor () private
void proto::EpiOutput_Day_Location::SharedDtor () private
void proto::EpiOutput_Day_Location::SetCachedSize (int size) const final private
void proto::EpiOutput_Day_Location::InternalSwap (EpiOutput_Day_Location * other) private
inline ::google::protobuf::Arena* proto::EpiOutput_Day_Location::GetArenaNoVirtual () const inline private
Definition at line 547 of file epioutput.pb.h.
Referenced by operator=().
void* proto::EpiOutput_Day_Location::MaybeArenaPtr () const inline private
Definition at line 550 of file epioutput.pb.h.
::google::protobuf::Metadata proto::EpiOutput_Day_Location::GetMetadata () const final
int proto::EpiOutput_Day_Location::agebrackets_size () const inline
Definition at line 1226 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_agebrackets () inline
Definition at line 1229 of file epioutput.pb.h.
References proto::EpiOutput_Day_Location_Coordinate::Clear().
proto::EpiOutput_Day_Location_AgeBracket * proto::EpiOutput_Day_Location::mutable_agebrackets (int index) inline
Definition at line 1232 of file epioutput.pb.h.
google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day_Location_AgeBracket > * proto::EpiOutput_Day_Location::mutable_agebrackets () inline
Definition at line 1237 of file epioutput.pb.h.
const ::proto::EpiOutput_Day_Location_AgeBracket & proto::EpiOutput_Day_Location::agebrackets (int index) const inline
Definition at line 1241 of file epioutput.pb.h.
proto::EpiOutput_Day_Location_AgeBracket * proto::EpiOutput_Day_Location::add_agebrackets () inline
Definition at line 1245 of file epioutput.pb.h.
const ::google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day_Location_AgeBracket > & proto::EpiOutput_Day_Location::agebrackets () const inline
Definition at line 1250 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_name () inline
Definition at line 1094 of file epioutput.pb.h.
const ::std::string & proto::EpiOutput_Day_Location::name () const inline
Definition at line 1097 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_name (const ::std::string & value) inline
Definition at line 1101 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_name (const char * value) inline
Definition at line 1114 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_name (const char * value, size_t size) inline
Definition at line 1120 of file epioutput.pb.h.
std::string * proto::EpiOutput_Day_Location::mutable_name () inline
Definition at line 1126 of file epioutput.pb.h.
std::string * proto::EpiOutput_Day_Location::release_name () inline
Definition at line 1131 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_allocated_name (::std::string * name) inline
Definition at line 1136 of file epioutput.pb.h.
bool proto::EpiOutput_Day_Location::has_coordinate () const inline
Definition at line 1175 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_coordinate () inline
Definition at line 1178 of file epioutput.pb.h.
const ::proto::EpiOutput_Day_Location_Coordinate & proto::EpiOutput_Day_Location::coordinate () const inline
Definition at line 1184 of file epioutput.pb.h.
References proto::_EpiOutput_Day_Location_Coordinate_default_instance_.
Referenced by visualization::EpiOutputProtoReader::Read().
proto::EpiOutput_Day_Location_Coordinate * proto::EpiOutput_Day_Location::release_coordinate () inline
Definition at line 1190 of file epioutput.pb.h.
proto::EpiOutput_Day_Location_Coordinate * proto::EpiOutput_Day_Location::mutable_coordinate () inline
Definition at line 1197 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_allocated_coordinate (::proto::EpiOutput_Day_Location_Coordinate * coordinate) inline
Definition at line 1206 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_id () inline
Definition at line 1080 of file epioutput.pb.h.
google::protobuf::int64 proto::EpiOutput_Day_Location::id () const inline
Definition at line 1083 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_id (::google::protobuf::int64 value) inline
Definition at line 1087 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_province () inline
Definition at line 1147 of file epioutput.pb.h.
google::protobuf::int64 proto::EpiOutput_Day_Location::province () const inline
Definition at line 1150 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_province (::google::protobuf::int64 value) inline
Definition at line 1154 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::clear_population () inline
Definition at line 1161 of file epioutput.pb.h.
google::protobuf::int64 proto::EpiOutput_Day_Location::population () const inline
Definition at line 1164 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location::set_population (::google::protobuf::int64 value) inline
Definition at line 1168 of file epioutput.pb.h.
Friends And Related Function Documentation
friend struct ::TableStruct_epioutput_2eproto friend
Definition at line 629 of file epioutput.pb.h.
void swap (EpiOutput_Day_Location & a, EpiOutput_Day_Location & b) friend
Definition at line 507 of file epioutput.pb.h.
Member Data Documentation
constexpr int proto::EpiOutput_Day_Location::kIndexInFileMessages static
Initial value:
=
    3
Definition at line 503 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kAgeBracketsFieldNumber = 6 static
Definition at line 567 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kNameFieldNumber = 2 static
Definition at line 578 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kCoordinateFieldNumber = 5 static
Definition at line 593 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kIdFieldNumber = 1 static
Definition at line 601 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kProvinceFieldNumber = 3 static
Definition at line 607 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location::kPopulationFieldNumber = 4 static
Definition at line 613 of file epioutput.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::EpiOutput_Day_Location::_internal_metadata_ private
Definition at line 619 of file epioutput.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day_Location_AgeBracket > proto::EpiOutput_Day_Location::agebrackets_ private
Definition at line 622 of file epioutput.pb.h.
::google::protobuf::internal::ArenaStringPtr proto::EpiOutput_Day_Location::name_ private
Definition at line 623 of file epioutput.pb.h.
::proto::EpiOutput_Day_Location_Coordinate* proto::EpiOutput_Day_Location::coordinate_ private
Definition at line 624 of file epioutput.pb.h.
::google::protobuf::int64 proto::EpiOutput_Day_Location::id_ private
Definition at line 625 of file epioutput.pb.h.
::google::protobuf::int64 proto::EpiOutput_Day_Location::province_ private
Definition at line 626 of file epioutput.pb.h.
::google::protobuf::int64 proto::EpiOutput_Day_Location::population_ private
Definition at line 627 of file epioutput.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::EpiOutput_Day_Location::_cached_size_ private
Definition at line 628 of file epioutput.pb.h.
The documentation for this class was generated from the following file:
epioutput.pb.h