Stride Reference Manual: visualization::MapController Class Reference
visualization::MapController Class Reference
MapController for use within the visualization, controller of the GUI and communicates with the qml.
#include <MapController.h>
Signals
void DayChanged ()
Signal for when day changes.
void HeightChanged ()
Signal for when height changes.
void WidthChanged ()
Signal for when width changes.
void ShownInformationChanged ()
Signal for when the show information changes.
void AgeBracketChanged ()
Signal for when the selected age bracket changes.
void HealthStatusChanged ()
Signal for when the selected health status changes.
void DataPinnedChanged ()
Signal for when the selected health status changes.
Public Member Functions
MapController (const std::string &filename)
Create a MapController and read the epi-output file.
MapController (const MapController &)=delete
No copy constructor.
MapController & operator= (const MapController &)=delete
No copy assignement.
void SetDay (const QString &day)
Set the shown day.
QString GetDay ()
Get the shown day.
void SetWindowHeight (const QString &height)
Set the window height.
void SetWindowWidth (const QString &width)
Set the window width.
void SetShownInformation (const QString &sourceInformation)
Set the shown information about one locality.
void Initialize (QObject *root)
Initialize the map.
void UpdateLocations ()
Update the color of the circles on the map.
void SetAgeBracket (const QString &ageBracket)
Set the selected age bracket.
void SetHealthStatus (const QString &healthStatus)
Set the selected health status.
bool IsDataPinned ()
Get the state of dataPinned.
void PinData (bool pinned)
Set the state of dataPinned.
Properties
QString shownDay
QString setWindowHeight
QString setWindowWidth
QString setShownInformation
QString setAgeBracket
QString setHealthStatus
bool dataPinned
Private Attributes
geopop::GeoGrid< EpiOutput > m_geogrid
GeoGrid that contains all the locations and their epi-output.
bool m_data_pinned
Indicates if the shown data is pinned.
unsigned int m_day
Current shown step.
unsigned int m_day_diff
Difference (Amount of days) between epi-output measurements (Stride)
unsigned int m_window_height
Height of the GUI window.
unsigned int m_window_width
Width of the GUI window.
std::string m_selectedAgeBracket
Selected age bracket in the GUI.
std::string m_selectedHealthStatus
Selected health status in the GUI.
std::map< std::string, std::map< std::string, double > > m_smallest_values
Smallest epi-output values for each category.
std::map< std::string, std::map< std::string, double > > m_biggest_values
Biggest epi-output values for each category.
QObject * m_root = nullptr
Root of the Qt object.
QString m_pinned_data
Information of the source of the last shown data.
Detailed Description
MapController for use within the visualization, controller of the GUI and communicates with the qml.
Definition at line 30 of file MapController.h.
Constructor & Destructor Documentation
visualization::MapController::MapController (const std::string & filename) explicit
Create a MapController and read the epi-output file.
Definition at line 65 of file MapController.cpp.
References geopop::GeoGrid< LocationContent >::begin(), visualization::EpiOutputReaderFactory::CreateReader(), geopop::GeoGrid< LocationContent >::Finalize(), m_day_diff, and m_geogrid.
visualization::MapController::MapController (const MapController &) delete
No copy constructor.
Member Function Documentation
MapController& visualization::MapController::operator= (const MapController &) delete
No copy assignement.
void visualization::MapController::SetDay (const QString & day)
Set the shown day.
Definition at line 81 of file MapController.cpp.
References m_data_pinned, m_day, m_day_diff, m_pinned_data, m_root, m_selectedAgeBracket, m_selectedHealthStatus, SetShownInformation(), and UpdateLocations().
QString visualization::MapController::GetDay ()
Get the shown day.
Definition at line 102 of file MapController.cpp.
References m_day.
void visualization::MapController::SetWindowHeight (const QString & height)
Set the window height.
Definition at line 104 of file MapController.cpp.
References m_window_height.
void visualization::MapController::SetWindowWidth (const QString & width)
Set the window width.
Definition at line 109 of file MapController.cpp.
References m_window_width.
void visualization::MapController::SetShownInformation (const QString & sourceInformation)
Set the shown information about one locality.
Definition at line 114 of file MapController.cpp.
References stride::ageBrackets, stride::healthStatuses, m_data_pinned, m_day, m_geogrid, m_pinned_data, m_root, and visualization::makePresentablePercentage().
Referenced by SetDay().
void visualization::MapController::Initialize (QObject * root)
Initialize the map.
Definition at line 218 of file MapController.cpp.
References geopop::GeoGrid< LocationContent >::begin(), visualization::distanceOnEarth(), geopop::GeoGrid< LocationContent >::end(), m_day, m_geogrid, m_root, m_window_height, and m_window_width.
Referenced by main().
void visualization::MapController::UpdateLocations ()
Update the color of the circles on the map.
Definition at line 339 of file MapController.cpp.
References stride::ageBrackets, m_day, m_geogrid, m_root, m_selectedAgeBracket, m_selectedHealthStatus, and visualization::makePresentablePercentage().
Referenced by SetAgeBracket(), SetDay(), and SetHealthStatus().
void visualization::MapController::SetAgeBracket (const QString & ageBracket)
Set the selected age bracket.
Definition at line 416 of file MapController.cpp.
References m_selectedAgeBracket, and UpdateLocations().
void visualization::MapController::SetHealthStatus (const QString & healthStatus)
Set the selected health status.
Definition at line 426 of file MapController.cpp.
References m_selectedHealthStatus, and UpdateLocations().
bool visualization::MapController::IsDataPinned ()
Get the state of dataPinned.
Definition at line 436 of file MapController.cpp.
References m_data_pinned.
void visualization::MapController::PinData (bool pinned)
Set the state of dataPinned.
Definition at line 438 of file MapController.cpp.
References m_data_pinned, and m_root.
void visualization::MapController::DayChanged () signal
Signal for when day changes.
void visualization::MapController::HeightChanged () signal
Signal for when height changes.
void visualization::MapController::WidthChanged () signal
Signal for when width changes.
void visualization::MapController::ShownInformationChanged () signal
Signal for when the show information changes.
void visualization::MapController::AgeBracketChanged () signal
Signal for when the selected age bracket changes.
void visualization::MapController::HealthStatusChanged () signal
Signal for when the selected health status changes.
void visualization::MapController::DataPinnedChanged () signal
Signal for when the selected health status changes.
Member Data Documentation
geopop::GeoGrid<EpiOutput> visualization::MapController::m_geogrid private
GeoGrid that contains all the locations and their epi-output.
Definition at line 108 of file MapController.h.
Referenced by Initialize(), MapController(), SetShownInformation(), and UpdateLocations().
bool visualization::MapController::m_data_pinned private
Indicates if the shown data is pinned.
Definition at line 110 of file MapController.h.
Referenced by IsDataPinned(), PinData(), SetDay(), and SetShownInformation().
unsigned int visualization::MapController::m_day private
Current shown step.
Definition at line 111 of file MapController.h.
Referenced by GetDay(), Initialize(), SetDay(), SetShownInformation(), and UpdateLocations().
unsigned int visualization::MapController::m_day_diff private
Difference (Amount of days) between epi-output measurements (Stride)
Definition at line 112 of file MapController.h.
Referenced by MapController(), and SetDay().
unsigned int visualization::MapController::m_window_height private
Height of the GUI window.
Definition at line 113 of file MapController.h.
Referenced by Initialize(), and SetWindowHeight().
unsigned int visualization::MapController::m_window_width private
Width of the GUI window.
Definition at line 114 of file MapController.h.
Referenced by Initialize(), and SetWindowWidth().
std::string visualization::MapController::m_selectedAgeBracket private
Selected age bracket in the GUI.
Definition at line 115 of file MapController.h.
Referenced by SetAgeBracket(), SetDay(), and UpdateLocations().
std::string visualization::MapController::m_selectedHealthStatus private
Selected health status in the GUI.
Definition at line 116 of file MapController.h.
Referenced by SetDay(), SetHealthStatus(), and UpdateLocations().
std::map<std::string, std::map<std::string, double> > visualization::MapController::m_smallest_values private
Smallest epi-output values for each category.
Definition at line 117 of file MapController.h.
std::map<std::string, std::map<std::string, double> > visualization::MapController::m_biggest_values private
Biggest epi-output values for each category.
Definition at line 118 of file MapController.h.
QObject* visualization::MapController::m_root = nullptr private
Root of the Qt object.
Definition at line 120 of file MapController.h.
Referenced by Initialize(), PinData(), SetDay(), SetShownInformation(), and UpdateLocations().
QString visualization::MapController::m_pinned_data private
Information of the source of the last shown data.
Definition at line 121 of file MapController.h.
Referenced by SetDay(), and SetShownInformation().
Property Documentation
QString visualization::MapController::shownDay read write
Definition at line 34 of file MapController.h.
QString visualization::MapController::setWindowHeight read write
Definition at line 35 of file MapController.h.
QString visualization::MapController::setWindowWidth read write
Definition at line 36 of file MapController.h.
QString visualization::MapController::setShownInformation read write
Definition at line 37 of file MapController.h.
QString visualization::MapController::setAgeBracket read write
Definition at line 38 of file MapController.h.
QString visualization::MapController::setHealthStatus read write
Definition at line 39 of file MapController.h.
bool visualization::MapController::dataPinned read write
Definition at line 40 of file MapController.h.
The documentation for this class was generated from the following files:
MapController.h
MapController.cpp