# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/stan/Desktop/UA/Bachelor_Eindwerk/stride

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/stan/Desktop/UA/Bachelor_Eindwerk/stride

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.13.4/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stan/Desktop/UA/Bachelor_Eindwerk/stride/CMakeFiles /Users/stan/Desktop/UA/Bachelor_Eindwerk/stride/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/stan/Desktop/UA/Bachelor_Eindwerk/stride/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stride

# Build rule for target.
stride: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stride
.PHONY : stride

# fast build rule for target.
stride/fast:
	$(MAKE) -f main/cpp/CMakeFiles/stride.dir/build.make main/cpp/CMakeFiles/stride.dir/build
.PHONY : stride/fast

#=============================================================================
# Target rules for targets named libstride

# Build rule for target.
libstride: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libstride
.PHONY : libstride

# fast build rule for target.
libstride/fast:
	$(MAKE) -f main/cpp/CMakeFiles/libstride.dir/build.make main/cpp/CMakeFiles/libstride.dir/build
.PHONY : libstride/fast

#=============================================================================
# Target rules for targets named pystride_swig_compilation

# Build rule for target.
pystride_swig_compilation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pystride_swig_compilation
.PHONY : pystride_swig_compilation

# fast build rule for target.
pystride_swig_compilation/fast:
	$(MAKE) -f main/python/CMakeFiles/pystride_swig_compilation.dir/build.make main/python/CMakeFiles/pystride_swig_compilation.dir/build
.PHONY : pystride_swig_compilation/fast

#=============================================================================
# Target rules for targets named pystride

# Build rule for target.
pystride: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pystride
.PHONY : pystride

# fast build rule for target.
pystride/fast:
	$(MAKE) -f main/python/CMakeFiles/pystride.dir/build.make main/python/CMakeFiles/pystride.dir/build
.PHONY : pystride/fast

#=============================================================================
# Target rules for targets named swigwrapper

# Build rule for target.
swigwrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 swigwrapper
.PHONY : swigwrapper

# fast build rule for target.
swigwrapper/fast:
	$(MAKE) -f main/python/CMakeFiles/swigwrapper.dir/build.make main/python/CMakeFiles/swigwrapper.dir/build
.PHONY : swigwrapper/fast

#=============================================================================
# Target rules for targets named sha1

# Build rule for target.
sha1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sha1
.PHONY : sha1

# fast build rule for target.
sha1/fast:
	$(MAKE) -f main/resources/lib/sha1/CMakeFiles/sha1.dir/build.make main/resources/lib/sha1/CMakeFiles/sha1.dir/build
.PHONY : sha1/fast

#=============================================================================
# Target rules for targets named trng

# Build rule for target.
trng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 trng
.PHONY : trng

# fast build rule for target.
trng/fast:
	$(MAKE) -f main/resources/lib/trng-4.20/CMakeFiles/trng.dir/build.make main/resources/lib/trng-4.20/CMakeFiles/trng.dir/build
.PHONY : trng/fast

#=============================================================================
# Target rules for targets named btester

# Build rule for target.
btester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 btester
.PHONY : btester

# fast build rule for target.
btester/fast:
	$(MAKE) -f test/cpp/btester/CMakeFiles/btester.dir/build.make test/cpp/btester/CMakeFiles/btester.dir/build
.PHONY : btester/fast

#=============================================================================
# Target rules for targets named gtester

# Build rule for target.
gtester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtester
.PHONY : gtester

# fast build rule for target.
gtester/fast:
	$(MAKE) -f test/cpp/gtester/CMakeFiles/gtester.dir/build.make test/cpp/gtester/CMakeFiles/gtester.dir/build
.PHONY : gtester/fast

#=============================================================================
# Target rules for targets named libmyhayai

# Build rule for target.
libmyhayai: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libmyhayai
.PHONY : libmyhayai

# fast build rule for target.
libmyhayai/fast:
	$(MAKE) -f test/cpp/myhayai/CMakeFiles/libmyhayai.dir/build.make test/cpp/myhayai/CMakeFiles/libmyhayai.dir/build
.PHONY : libmyhayai/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f test/resources/lib/gtest/CMakeFiles/gtest.dir/build.make test/resources/lib/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... stride"
	@echo "... libstride"
	@echo "... pystride_swig_compilation"
	@echo "... pystride"
	@echo "... swigwrapper"
	@echo "... sha1"
	@echo "... trng"
	@echo "... btester"
	@echo "... gtester"
	@echo "... libmyhayai"
	@echo "... gtest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

