Stride Reference Manual: geopop::GeoGridHDF5Writer Class Reference
geopop::GeoGridHDF5Writer Class Reference
An implementation of the GeoGridFileWriter using HDF5 This class is used to write a GeoGrid to an HDF5 file.
#include <GeoGridHDF5Writer.h>
Public Member Functions
GeoGridHDF5Writer ()=delete
GeoGridProtoWriter cannot be instantiated without providing a file name.
GeoGridHDF5Writer (std::string fileName)
Construct GeoGridHDF5Writer for provided file name.
~GeoGridHDF5Writer () override=default
Default destructor.
void Write (GeoGrid< Epidemiologic > &geoGrid) override
Write the GeoGrid to the file in HDF5 format.
Public Member Functions inherited from geopop::GeoGridFileWriter
GeoGridFileWriter ()=delete
GeoGridFileWriter cannot be instantiated without filename.
GeoGridFileWriter (std::string fileName)
Construct GeoGridFileWriter referencing given filename.
~GeoGridFileWriter () override=default
Default destructor.
std::string FileName ()
Return file name.
Public Member Functions inherited from geopop::GeoGridWriter
GeoGridWriter ()=default
Default construtor.
virtual ~GeoGridWriter ()=default
Virtual destrutor to make class abstract.
Private Member Functions
void WriteLocation (geopop::Location< Epidemiologic > &loc, H5::Group &locsGroup)
void WriteCommutes (const vector< pair< Epidemiologic *, double >> &commutes, H5::Group &locGroup)
void WriteContactPool (const stride::ContactPool &pool, stride::ContactType::Id type, H5::Group &cpGroup)
void WritePeople (H5::Group &rootGroup)
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
unsigned int m_location_counter
unsigned int m_pool_counter
Additional Inherited Members
Protected Attributes inherited from geopop::GeoGridFileWriter
std::string m_file_name
Detailed Description
An implementation of the GeoGridFileWriter using HDF5 This class is used to write a GeoGrid to an HDF5 file.
Definition at line 35 of file GeoGridHDF5Writer.h.
Constructor & Destructor Documentation
geopop::GeoGridHDF5Writer::GeoGridHDF5Writer () delete
GeoGridProtoWriter cannot be instantiated without providing a file name.
geopop::GeoGridHDF5Writer::GeoGridHDF5Writer (std::string fileName) explicit
Construct GeoGridHDF5Writer for provided file name.
Definition at line 33 of file GeoGridHDF5Writer.cpp.
geopop::GeoGridHDF5Writer::~GeoGridHDF5Writer () override default
Default destructor.
Member Function Documentation
void geopop::GeoGridHDF5Writer::Write (GeoGrid< Epidemiologic > & geoGrid) override virtual
Write the GeoGrid to the file in HDF5 format.
Implements geopop::GeoGridFileWriter.
Definition at line 38 of file GeoGridHDF5Writer.cpp.
References geopop::GeoGridFileWriter::m_file_name, m_persons_found, geopop::GeoGrid< LocationContent >::size(), H5Utils::WriteAttribute(), WriteLocation(), and WritePeople().
void geopop::GeoGridHDF5Writer::WriteLocation (geopop::Location< Epidemiologic > & loc, H5::Group & locsGroup) private
Create group for location
Set location attributes
Definition at line 64 of file GeoGridHDF5Writer.cpp.
References geopop::Location< Content >::GetContent(), geopop::Location< Content >::GetCoordinate(), geopop::Location< Content >::GetID(), geopop::Location< Content >::GetName(), geopop::Location< Content >::GetProvince(), stride::ContactType::IdList, m_location_counter, m_pool_counter, H5Utils::WriteAttribute(), WriteCommutes(), and WriteContactPool().
Referenced by Write().
void geopop::GeoGridHDF5Writer::WriteCommutes (const vector< pair< Epidemiologic *, double >> & commutes, H5::Group & locGroup) private
Create compound datatype
Create dataset
Definition at line 90 of file GeoGridHDF5Writer.cpp.
References H5Utils::CreateSpace(), H5Utils::GetCompoundType< H5Commute >(), and H5Utils::WriteAttribute().
Referenced by WriteLocation().
void geopop::GeoGridHDF5Writer::WriteContactPool (const stride::ContactPool & pool, stride::ContactType::Id type, H5::Group & cpGroup) private
Create dataset
Definition at line 108 of file GeoGridHDF5Writer.cpp.
References H5Utils::CreateSpace(), H5Utils::GetCompoundType< H5PoolPerson >(), stride::ContactPool::GetId(), m_persons_found, m_pool_counter, stride::ContactPool::size(), stride::ContactLogMode::ToString(), and H5Utils::WriteAttribute().
Referenced by WriteLocation().
void geopop::GeoGridHDF5Writer::WritePeople (H5::Group & rootGroup) private
Create compound datatype
Create dataset
Definition at line 129 of file GeoGridHDF5Writer.cpp.
References H5Utils::CreateSpace(), H5Utils::GetCompoundType< H5Person >(), m_persons_found, and H5Utils::WriteAttribute().
Referenced by Write().
Member Data Documentation
std::set<stride::Person*> geopop::GeoGridHDF5Writer::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 60 of file GeoGridHDF5Writer.h.
Referenced by Write(), WriteContactPool(), and WritePeople().
unsigned int geopop::GeoGridHDF5Writer::m_location_counter private
Definition at line 61 of file GeoGridHDF5Writer.h.
Referenced by WriteLocation().
unsigned int geopop::GeoGridHDF5Writer::m_pool_counter private
Definition at line 62 of file GeoGridHDF5Writer.h.
Referenced by WriteContactPool(), and WriteLocation().
The documentation for this class was generated from the following files:
GeoGridHDF5Writer.h
GeoGridHDF5Writer.cpp