Stride Reference Manual: geopop::EpiOutputHDF5Writer Class Reference
geopop::EpiOutputHDF5Writer Class Reference
Writes a GeoGrid epi-output to a HDF5 file.
#include <EpiOutputHDF5Writer.h>
Public Member Functions
EpiOutputHDF5Writer (const std::string &filename)
Construct the EpiOutputHDF5Writer.
void Write () override
Write the provided GeoGrid epi-output to the provided HDF5 file. (If given)
void Update (GeoGrid< Epidemiologic > &geoGrid, unsigned int day) override
Write the epi-output of the GeoGrid to the right data format.
Public Member Functions inherited from geopop::EpiOutputWriter
virtual ~EpiOutputWriter ()=default
Deconstruct the Writer.
Private Attributes
H5::H5File m_output
HDF5 file.
unsigned int m_day_count
Used to set day_count attribute in HDF5 file.
unsigned int m_location_count
Used to set location_count attribute in HDF5 file.
Detailed Description
Writes a GeoGrid epi-output to a HDF5 file.
Definition at line 28 of file EpiOutputHDF5Writer.h.
Constructor & Destructor Documentation
geopop::EpiOutputHDF5Writer::EpiOutputHDF5Writer (const std::string & filename) explicit
Construct the EpiOutputHDF5Writer.
Definition at line 35 of file EpiOutputHDF5Writer.cpp.
References m_output.
Member Function Documentation
void geopop::EpiOutputHDF5Writer::Write () override virtual
Write the provided GeoGrid epi-output to the provided HDF5 file. (If given)
Implements geopop::EpiOutputWriter.
Definition at line 42 of file EpiOutputHDF5Writer.cpp.
References m_day_count, m_output, and H5Utils::WriteAttribute().
void geopop::EpiOutputHDF5Writer::Update (GeoGrid< Epidemiologic > & geoGrid, unsigned int day) override virtual
Write the epi-output of the GeoGrid to the right data format.
Implements geopop::EpiOutputWriter.
Definition at line 48 of file EpiOutputHDF5Writer.cpp.
References stride::ageBrackets, H5Utils::CreateSpace(), H5Utils::GetCompoundType< H5EpiOutput >(), stride::healthStatuses, m_day_count, m_location_count, m_output, geopop::GeoGrid< LocationContent >::size(), and H5Utils::WriteAttribute().
Member Data Documentation
H5::H5File geopop::EpiOutputHDF5Writer::m_output private
HDF5 file.
Definition at line 41 of file EpiOutputHDF5Writer.h.
Referenced by EpiOutputHDF5Writer(), Update(), and Write().
unsigned int geopop::EpiOutputHDF5Writer::m_day_count private
Used to set day_count attribute in HDF5 file.
Definition at line 42 of file EpiOutputHDF5Writer.h.
Referenced by Update(), and Write().
unsigned int geopop::EpiOutputHDF5Writer::m_location_count private
Used to set location_count attribute in HDF5 file.
Definition at line 43 of file EpiOutputHDF5Writer.h.
Referenced by Update().
The documentation for this class was generated from the following files:
EpiOutputHDF5Writer.h
EpiOutputHDF5Writer.cpp