Stride Reference Manual: visualization::EpiOutputProtoReader Class Reference
visualization::EpiOutputProtoReader Class Reference
An implementation of the EpiOutputReader using Protobuf.
#include <EpiOutputProtoReader.h>
Public Member Functions
EpiOutputProtoReader (std::unique_ptr< std::istream > inputStream, geopop::GeoGrid< EpiOutput > *epiOutput)
Construct the EpiOutputProtoReader with the istream which contains the Protobuf.
EpiOutputProtoReader (const EpiOutputProtoReader &)=delete
No copy constructor.
EpiOutputProtoReader operator= (const EpiOutputProtoReader &)=delete
No copy assignement.
void Read () override
Actually perform the read and return the EpiOutput.
Public Member Functions inherited from visualization::EpiOutputReader
EpiOutputReader (geopop::GeoGrid< EpiOutput > *epiOutput)
Parametrized constructor.
EpiOutputReader (const EpiOutputReader &)=delete
No copy constructor.
EpiOutputReader & operator= (const EpiOutputReader &)=delete
No copy assignement.
virtual ~EpiOutputReader ()=default
Default destructor.
Private Attributes
std::unique_ptr< std::istream > m_inputStream
File to read.
Additional Inherited Members
Protected Attributes inherited from visualization::EpiOutputReader
geopop::GeoGrid< EpiOutput > * m_epiOutput
Resulting epi-output.
Detailed Description
An implementation of the EpiOutputReader using Protobuf.
This class is used to read a epi-output from a Protobuf file.
Definition at line 30 of file EpiOutputProtoReader.h.
Constructor & Destructor Documentation
visualization::EpiOutputProtoReader::EpiOutputProtoReader (std::unique_ptr< std::istream > inputStream, geopop::GeoGrid< EpiOutput > * epiOutput)
Construct the EpiOutputProtoReader with the istream which contains the Protobuf.
Definition at line 29 of file EpiOutputProtoReader.cpp.
visualization::EpiOutputProtoReader::EpiOutputProtoReader (const EpiOutputProtoReader &) delete
No copy constructor.
Member Function Documentation
EpiOutputProtoReader visualization::EpiOutputProtoReader::operator= (const EpiOutputProtoReader &) delete
No copy assignement.
void visualization::EpiOutputProtoReader::Read () override virtual
Actually perform the read and return the EpiOutput.
Implements visualization::EpiOutputReader.
Definition at line 35 of file EpiOutputProtoReader.cpp.
References proto::EpiOutput_Day_Location::coordinate(), proto::EpiOutput::days(), proto::EpiOutput::days_size(), proto::EpiOutput_Day::locations(), visualization::EpiOutputReader::m_epiOutput, and m_inputStream.
Member Data Documentation
std::unique_ptr<std::istream> visualization::EpiOutputProtoReader::m_inputStream private
File to read.
Definition at line 46 of file EpiOutputProtoReader.h.
Referenced by Read().
The documentation for this class was generated from the following files:
EpiOutputProtoReader.h
EpiOutputProtoReader.cpp