Stride Reference Manual: proto::EpiOutput Class Reference
proto::EpiOutput Class Reference final
#include <epioutput.pb.h>
Public Types
typedef EpiOutput_Day Day
Public Member Functions
EpiOutput ()
virtual ~EpiOutput ()
EpiOutput (const EpiOutput &from)
EpiOutput & operator= (const EpiOutput &from)
void Swap (EpiOutput *other)
EpiOutput * New () const final
EpiOutput * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const EpiOutput &from)
void MergeFrom (const EpiOutput &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int days_size () const
void clear_days ()
::proto::EpiOutput_Day * mutable_days (int index)
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day > * mutable_days ()
const ::proto::EpiOutput_Day & days (int index) const
::proto::EpiOutput_Day * add_days ()
const ::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day > & days () const
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const EpiOutput & default_instance ()
static void InitAsDefaultInstance ()
static const EpiOutput * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kDaysFieldNumber = 1
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (EpiOutput *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day > days_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_epioutput_2eproto
void swap (EpiOutput &a, EpiOutput &b)
Detailed Description
Definition at line 760 of file epioutput.pb.h.
Member Typedef Documentation
typedef EpiOutput_Day proto::EpiOutput::Day
Definition at line 853 of file epioutput.pb.h.
Constructor & Destructor Documentation
proto::EpiOutput::EpiOutput ()
virtual proto::EpiOutput::~EpiOutput () virtual
proto::EpiOutput::EpiOutput (const EpiOutput & from)
Member Function Documentation
EpiOutput& proto::EpiOutput::operator= (const EpiOutput & from) inline
Definition at line 768 of file epioutput.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::EpiOutput::descriptor () inline static
Definition at line 787 of file epioutput.pb.h.
static const EpiOutput& proto::EpiOutput::default_instance () static
static void proto::EpiOutput::InitAsDefaultInstance () static
static const EpiOutput* proto::EpiOutput::internal_default_instance () inline static
Definition at line 793 of file epioutput.pb.h.
References proto::_EpiOutput_default_instance_.
void proto::EpiOutput::Swap (EpiOutput * other)
EpiOutput* proto::EpiOutput::New () const inline final
Definition at line 807 of file epioutput.pb.h.
EpiOutput* proto::EpiOutput::New (::google::protobuf::Arena * arena) const inline final
Definition at line 811 of file epioutput.pb.h.
void proto::EpiOutput::CopyFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput::MergeFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput::CopyFrom (const EpiOutput & from)
void proto::EpiOutput::MergeFrom (const EpiOutput & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::EpiOutput::Clear () final
bool proto::EpiOutput::IsInitialized () const final
size_t proto::EpiOutput::ByteSizeLong () const final
bool proto::EpiOutput::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::EpiOutput::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::EpiOutput::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::EpiOutput::GetCachedSize () const inline final
Definition at line 833 of file epioutput.pb.h.
void proto::EpiOutput::SharedCtor () private
void proto::EpiOutput::SharedDtor () private
void proto::EpiOutput::SetCachedSize (int size) const final private
void proto::EpiOutput::InternalSwap (EpiOutput * other) private
inline ::google::protobuf::Arena* proto::EpiOutput::GetArenaNoVirtual () const inline private
Definition at line 841 of file epioutput.pb.h.
Referenced by operator=().
void* proto::EpiOutput::MaybeArenaPtr () const inline private
Definition at line 844 of file epioutput.pb.h.
::google::protobuf::Metadata proto::EpiOutput::GetMetadata () const final
int EpiOutput::days_size () const inline
Definition at line 1308 of file epioutput.pb.h.
Referenced by visualization::EpiOutputProtoReader::Read().
void EpiOutput::clear_days () inline
Definition at line 1311 of file epioutput.pb.h.
proto::EpiOutput_Day * EpiOutput::mutable_days (int index) inline
Definition at line 1314 of file epioutput.pb.h.
google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day > * EpiOutput::mutable_days () inline
Definition at line 1319 of file epioutput.pb.h.
const ::proto::EpiOutput_Day & EpiOutput::days (int index) const inline
Definition at line 1323 of file epioutput.pb.h.
Referenced by visualization::EpiOutputProtoReader::Read().
proto::EpiOutput_Day * EpiOutput::add_days () inline
Definition at line 1327 of file epioutput.pb.h.
Referenced by geopop::EpiOutputProtoWriter::Update().
const ::google::protobuf::RepeatedPtrField<::proto::EpiOutput_Day > & EpiOutput::days () const inline
Definition at line 1332 of file epioutput.pb.h.
Friends And Related Function Documentation
friend struct ::TableStruct_epioutput_2eproto friend
Definition at line 876 of file epioutput.pb.h.
void swap (EpiOutput & a, EpiOutput & b) friend
Definition at line 801 of file epioutput.pb.h.
Member Data Documentation
constexpr int proto::EpiOutput::kIndexInFileMessages static
Initial value:
=
    5
Definition at line 797 of file epioutput.pb.h.
const int proto::EpiOutput::kDaysFieldNumber = 1 static
Definition at line 860 of file epioutput.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::EpiOutput::_internal_metadata_ private
Definition at line 871 of file epioutput.pb.h.
::google::protobuf::RepeatedPtrField< ::proto::EpiOutput_Day > proto::EpiOutput::days_ private
Definition at line 874 of file epioutput.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::EpiOutput::_cached_size_ private
Definition at line 875 of file epioutput.pb.h.
The documentation for this class was generated from the following file:
epioutput.pb.h