Stride Reference Manual: geopop::Generator< ID > Class Template Reference
geopop::Generator< ID > Class Template Reference
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
#include <Generator.h>
Public Member Functions
Generator (stride::util::RnMan rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Constructor with random number manager and logger.
~Generator ()=default
Default is OK.
void Apply (GeoGrid< Epidemiologic > &, const GeoGridConfig &)
Generate ContactPools for ContactType::Id as sepcified by data in GeoGridConfig.
void AddPools (Location< Epidemiologic > &loc, stride::Population *pop, const GeoGridConfig &ggConfig, unsigned int limit=std::numeric_limits< unsigned int >::infinity())
Create a given number ContactPools in the GeoGrid.
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void AddPools (Location< Epidemiologic > &loc, stride::Population *pop, const GeoGridConfig &ggConfig, unsigned int limit)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void AddPools (Location< Epidemiologic > &loc, stride::Population *pop, const GeoGridConfig &ggConfig, unsigned int limit)
Protected Attributes
stride::util::RnMan m_rn_man
RnManager used by generators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by generators.
Detailed Description
template<typename stride::ContactType::Id ID>
class geopop::Generator< ID >
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
Definition at line 39 of file Generator.h.
Constructor & Destructor Documentation
template<typename stride::ContactType::Id ID> geopop::Generator< ID >::Generator (stride::util::RnMan rnMan, std::shared_ptr< spdlog::logger > logger = nullptr) inline explicit
Constructor with random number manager and logger.
Definition at line 43 of file Generator.h.
References stride::util::LogUtils::CreateNullLogger(), geopop::Generator< ID >::m_logger, and geopop::Generator< ID >::~Generator().
template<typename stride::ContactType::Id ID> geopop::Generator< ID >::~Generator () default
Default is OK.
Referenced by geopop::Generator< ID >::Generator().
Member Function Documentation
template<typename stride::ContactType::Id ID> void geopop::Generator< ID >::Apply (GeoGrid< Epidemiologic > & , const GeoGridConfig &) inline
Generate ContactPools for ContactType::Id as sepcified by data in GeoGridConfig.
Definition at line 54 of file Generator.h.
template<typename stride::ContactType::Id ID> void geopop::Generator< ID >::AddPools (Location< Epidemiologic > & loc, stride::Population * pop, const GeoGridConfig & ggConfig, unsigned int limit = std::numeric_limits<unsigned int>::infinity()) inline
Create a given number ContactPools in the GeoGrid.
Definition at line 57 of file Generator.h.
References stride::ContactPoolSys::CreateContactPool(), geopop::Location< Content >::GetContent(), geopop::GeoGridConfig::pools, and stride::Population::RefPoolSys().
template<> void geopop::Generator< stride::ContactType::Id::College >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 27 of file CollegeGenerator.cpp.
References AssertThrow, geopop::GeoGrid< LocationContent >::GetPopulation(), geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, geopop::PopulationInfo::popcount_college, and geopop::GeoGrid< LocationContent >::TopK().
template<> void geopop::Generator< stride::ContactType::Id::Daycare >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file DaycareGenerator.cpp.
References geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, and geopop::PopulationInfo::popcount_daycare.
template<> void geopop::Generator< stride::ContactType::Id::Daycare >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::PreSchool >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::K12School >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::College >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Household >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::AddPools (Location< Epidemiologic > & loc, stride::Population * pop, const GeoGridConfig & ggConfig, unsigned int limit)
template<> void geopop::Generator< stride::ContactType::Id::Household >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file HouseholdGenerator.cpp.
References geopop::PopulationInfo::count_households, and geopop::GeoGridConfig::info.
template<> void geopop::Generator< stride::ContactType::Id::K12School >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file K12SchoolGenerator.cpp.
References geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, and geopop::PopulationInfo::popcount_k12school.
template<> void geopop::Generator< stride::ContactType::Id::PreSchool >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 25 of file PreSchoolGenerator.cpp.
References geopop::GeoGridConfig::info, geopop::GeoGridConfig::people, and geopop::PopulationInfo::popcount_preschool.
template<> void geopop::Generator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file PrimaryCommunityGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::param, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::pop_size.
template<> void geopop::Generator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file SecondaryCommunityGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::param, geopop::GeoGridConfig::people, and geopop::GeoGridConfig::pop_size.
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 27 of file WorkplaceGenerator.cpp.
References AssertThrow, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::info, geopop::GeoGridConfig::param, geopop::GeoGridConfig::participation_workplace, geopop::GeoGridConfig::people, geopop::PopulationInfo::popcount_workplace, and geopop::GeoGridConfig::work_distribution.
template<> void geopop::Generator< stride::ContactType::Id::Workplace >::AddPools (Location< Epidemiologic > & loc, stride::Population * pop, const GeoGridConfig & ggConfig, unsigned int limit)
Definition at line 117 of file WorkplaceGenerator.cpp.
References stride::ContactPoolSys::CreateContactPool(), geopop::Location< Content >::GetContent(), stride::Population::RefPoolSys(), and stride::ContactType::Workplace.
Member Data Documentation
template<typename stride::ContactType::Id ID> stride::util::RnMan geopop::Generator< ID >::m_rn_man protected
RnManager used by generators.
Definition at line 68 of file Generator.h.
template<typename stride::ContactType::Id ID> std::shared_ptr<spdlog::logger> geopop::Generator< ID >::m_logger protected
Logger used by generators.
Definition at line 69 of file Generator.h.
Referenced by geopop::Generator< ID >::Generator().
The documentation for this class was generated from the following file:
Generator.h