Stride Reference Manual: geopop::GeoGridFileWriter Class Reference
geopop::GeoGridFileWriter Class Reference abstract
An interface for writing the GeoGrid to a filelocated at inputFilePath, can be implemented with multiple file types.
#include <GeoGridFileWriter.h>
Public Member Functions
GeoGridFileWriter ()=delete
GeoGridFileWriter cannot be instantiated without filename.
GeoGridFileWriter (std::string fileName)
Construct GeoGridFileWriter referencing given filename.
~GeoGridFileWriter () override=default
Default destructor.
void Write (GeoGrid< Epidemiologic > &geoGrid) override=0
Write the GeoGrid to file.
std::string FileName ()
Return file name.
Public Member Functions inherited from geopop::GeoGridWriter
GeoGridWriter ()=default
Default construtor.
virtual ~GeoGridWriter ()=default
Virtual destrutor to make class abstract.
Protected Attributes
std::string m_file_name
Detailed Description
An interface for writing the GeoGrid to a filelocated at inputFilePath, can be implemented with multiple file types.
HDF5 is currently implemented.
Definition at line 34 of file GeoGridFileWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridFileWriter::GeoGridFileWriter () delete
GeoGridFileWriter cannot be instantiated without filename.
geopop::GeoGridFileWriter::GeoGridFileWriter (std::string fileName) inline explicit
Construct GeoGridFileWriter referencing given filename.
Definition at line 41 of file GeoGridFileWriter.h.
References Write(), and ~GeoGridFileWriter().
geopop::GeoGridFileWriter::~GeoGridFileWriter () override default
Default destructor.
Referenced by GeoGridFileWriter().
Member Function Documentation
void geopop::GeoGridFileWriter::Write (GeoGrid< Epidemiologic > & geoGrid) override pure virtual
Write the GeoGrid to file.
Implements geopop::GeoGridWriter.
Implemented in geopop::GeoGridHDF5Writer.
Referenced by GeoGridFileWriter().
std::string geopop::GeoGridFileWriter::FileName () inline
Return file name.
Definition at line 50 of file GeoGridFileWriter.h.
References m_file_name.
Member Data Documentation
std::string geopop::GeoGridFileWriter::m_file_name protected
Definition at line 53 of file GeoGridFileWriter.h.
Referenced by FileName(), and geopop::GeoGridHDF5Writer::Write().
The documentation for this class was generated from the following file:
GeoGridFileWriter.h