Stride Reference Manual: geopop::Epidemiologic Class Reference
geopop::Epidemiologic Class Reference
Epidemiologic for use within the GeoGrid, contains index to ContactPools and commutes.
#include <Epidemiologic.h>
Public Member Functions
Epidemiologic (Location< Epidemiologic > *location, unsigned int popCount=0U, unsigned int householdType=0U, double youngOldFraction=1.0)
Parametrized constructor with population count.
Epidemiologic (const Epidemiologic &)=delete
No copy constructor.
Epidemiologic operator= (const Epidemiologic &)=delete
No copy assignment.
bool operator== (const Epidemiologic &other) const
Perform a full comparison with the other Epidemiologic.
void AddIncomingCommute (std::shared_ptr< Epidemiologic > otherEpidemiologic, double fraction)
Adds a Epidemiologic and a proportion to the incoming commute vector.
void AddOutgoingCommute (std::shared_ptr< Epidemiologic > otherEpidemiologic, double fraction)
Adds a Epidemiologic and a fraction to the outgoing commute vector.
int GetIncomingCommuteCount (double fractionCommuters) const
Calculates number of incomming commuters, given the fraction of the population that commutes.
unsigned int GetInfectedCount () const
Gets the number of people infected in the contactpools at this Epidemiologic.
unsigned int GetOutgoingCommuteCount (double fractionCommuters) const
Calculates number of outgoing commuters, given the fraction of the population that commutes.
unsigned int GetPopCount () const
Gets the absolute population.
unsigned int GetMemberCount () const
Gets the amount of members in all household pools.
double GetPopFraction () const
Get Epidemiologic's population fraction (of the total population count).
unsigned int GetID () const
Get the ID of the location.
Location< Epidemiologic > * GetLocation () const
Get the location of which this is the content.
unsigned int GetHouseHoldType () const
Get household type for Households references.
double GetYoungOldFraction () const
Gets young/old fraction.
std::map< std::string, std::map< std::string, double > > const GenerateEpiOutput ()
Generate an epi-output map of the Household contactpools.
void SetPopCount (unsigned int totalPopCount)
Set Epidemiologic's population count using its population fraction and the total population count.
void SetPopFraction (double relativePopulation)
Set Epidemiologic's population fraction (of the total population count).
void SetHouseHoldType (unsigned int houseHoldType)
Set household type for Households references.
void SetYoungOldFraction (double youngOldFraction)
Sets young/old fraction.
const stride::util::SegmentedVector< stride::ContactPool * > & CRefPools (stride::ContactType::Id id) const
Access through const reference to ContactPools of type 'id'.
template<stride::ContactType::Id T>
const stride::util::SegmentedVector< stride::ContactPool * > & CRefPools () const
Templated version of for use when the type id is fixed.
stride::util::SegmentedVector< stride::ContactPool * > & RefPools (stride::ContactType::Id id)
Access through reference to ContactPools of type 'id'.
template<stride::ContactType::Id T>
stride::util::SegmentedVector< stride::ContactPool * > & RefPools ()
Templated version of for use when the type id is fixed.
void RegisterPool (stride::ContactPool *p, stride::ContactType::Id typeId)
Register a ContactPool pointer in this Epidemiologic's pool system.
template<stride::ContactType::Id T>
void RegisterPool (stride::ContactPool *p)
Templated version of .
const std::vector< std::pair< Epidemiologic *, double > > & CRefIncomingCommutes () const
References incoming commute Epidemiologics + fraction of commutes to that Epidemiologic.
const std::vector< std::pair< Epidemiologic *, double > > & CRefOutgoingCommutes () const
References outgoing commute Epidemiologics + fraction of commutes to that Epidemiologic.
Private Attributes
unsigned int m_pop_count
Population count (number of individuals) at this Epidemiologic.
double m_pop_fraction
Fraction of whole population at this Epidemiologic.
Location< Epidemiologic > * m_location
Link to the location.
unsigned int m_household_type
Household type.
double m_young_old_fraction
Young/Old fraction (ratio between 15-24y and 55-64y old persons).
std::vector< std::pair< Epidemiologic *, double > > m_inCommutes
Incomming commutes stored as pair of Epidemiologic and fraction of population at that Epidemiologic.
std::vector< std::pair< Epidemiologic *, double > > m_outCommutes
The system holding pointers to the contactpools (for each type id) at this Epidemiologic.
stride::ContactType::IdSubscriptArray< stride::util::SegmentedVector< stride::ContactPool * > > m_pool_index
Detailed Description
Epidemiologic for use within the GeoGrid, contains index to ContactPools and commutes.
Definition at line 44 of file Epidemiologic.h.
Constructor & Destructor Documentation
geopop::Epidemiologic::Epidemiologic (Location< Epidemiologic > * location, unsigned int popCount = 0U, unsigned int householdType = 0U, double youngOldFraction = 1.0) explicit
Parametrized constructor with population count.
Definition at line 32 of file Epidemiologic.cpp.
geopop::Epidemiologic::Epidemiologic (const Epidemiologic &) delete
No copy constructor.
Member Function Documentation
Epidemiologic geopop::Epidemiologic::operator= (const Epidemiologic &) delete
No copy assignment.
bool geopop::Epidemiologic::operator== (const Epidemiologic & other) const
Perform a full comparison with the other Epidemiologic.
Definition at line 39 of file Epidemiologic.cpp.
References CRefIncomingCommutes(), CRefOutgoingCommutes(), CRefPools(), GetHouseHoldType(), GetPopCount(), GetYoungOldFraction(), and stride::ContactType::IdList.
void geopop::Epidemiologic::AddIncomingCommute (std::shared_ptr< Epidemiologic > otherEpidemiologic, double fraction)
Adds a Epidemiologic and a proportion to the incoming commute vector.
I.e. fraction of commuting population at otherEpidemiologic commuting to this Epidemiologic.
Definition at line 50 of file Epidemiologic.cpp.
References m_inCommutes.
void geopop::Epidemiologic::AddOutgoingCommute (std::shared_ptr< Epidemiologic > otherEpidemiologic, double fraction)
Adds a Epidemiologic and a fraction to the outgoing commute vector.
I.e. fraction of commuting population at this Epidemiologic commuting to otherEpidemiologic.
Definition at line 55 of file Epidemiologic.cpp.
References m_outCommutes.
int geopop::Epidemiologic::GetIncomingCommuteCount (double fractionCommuters) const
Calculates number of incomming commuters, given the fraction of the population that commutes.
Definition at line 60 of file Epidemiologic.cpp.
References m_inCommutes.
unsigned int geopop::Epidemiologic::GetInfectedCount () const
Gets the number of people infected in the contactpools at this Epidemiologic.
Definition at line 70 of file Epidemiologic.cpp.
unsigned int geopop::Epidemiologic::GetOutgoingCommuteCount (double fractionCommuters) const
Calculates number of outgoing commuters, given the fraction of the population that commutes.
Definition at line 82 of file Epidemiologic.cpp.
References m_outCommutes, and m_pop_count.
unsigned int geopop::Epidemiologic::GetPopCount () const inline
Gets the absolute population.
Definition at line 78 of file Epidemiologic.h.
References GetID(), GetMemberCount(), GetPopFraction(), and m_pop_count.
Referenced by operator==().
unsigned int geopop::Epidemiologic::GetMemberCount () const
Gets the amount of members in all household pools.
Definition at line 92 of file Epidemiologic.cpp.
References CRefPools(), and stride::ContactType::Household.
Referenced by GenerateEpiOutput(), and GetPopCount().
double geopop::Epidemiologic::GetPopFraction () const
Get Epidemiologic's population fraction (of the total population count).
Definition at line 101 of file Epidemiologic.cpp.
References m_pop_fraction.
Referenced by GetPopCount().
unsigned int geopop::Epidemiologic::GetID () const
Get the ID of the location.
Definition at line 103 of file Epidemiologic.cpp.
References m_location.
Referenced by GetPopCount().
Location<Epidemiologic>* geopop::Epidemiologic::GetLocation () const inline
Get the location of which this is the content.
Definition at line 90 of file Epidemiologic.h.
References m_location.
unsigned int geopop::Epidemiologic::GetHouseHoldType () const inline
Get household type for Households references.
Definition at line 93 of file Epidemiologic.h.
References m_household_type.
Referenced by operator==().
double geopop::Epidemiologic::GetYoungOldFraction () const inline
Gets young/old fraction.
Definition at line 96 of file Epidemiologic.h.
References GenerateEpiOutput(), m_young_old_fraction, SetPopCount(), and SetPopFraction().
Referenced by operator==().
std::map< std::string, std::map< std::string, double > > const geopop::Epidemiologic::GenerateEpiOutput ()
Generate an epi-output map of the Household contactpools.
Definition at line 105 of file Epidemiologic.cpp.
References stride::ageBrackets, CRefPools(), GetMemberCount(), stride::healthStatuses, and stride::ContactType::Household.
Referenced by GetYoungOldFraction().
void geopop::Epidemiologic::SetPopCount (unsigned int totalPopCount)
Set Epidemiologic's population count using its population fraction and the total population count.
Definition at line 152 of file Epidemiologic.cpp.
References m_pop_count, and m_pop_fraction.
Referenced by GetYoungOldFraction().
void geopop::Epidemiologic::SetPopFraction (double relativePopulation)
Set Epidemiologic's population fraction (of the total population count).
Definition at line 156 of file Epidemiologic.cpp.
References m_pop_fraction.
Referenced by GetYoungOldFraction().
void geopop::Epidemiologic::SetHouseHoldType (unsigned int houseHoldType) inline
Set household type for Households references.
Definition at line 108 of file Epidemiologic.h.
References m_household_type.
void geopop::Epidemiologic::SetYoungOldFraction (double youngOldFraction) inline
Sets young/old fraction.
Definition at line 111 of file Epidemiologic.h.
References m_young_old_fraction.
const stride::util::SegmentedVector<stride::ContactPool*>& geopop::Epidemiologic::CRefPools (stride::ContactType::Id id) const inline
Access through const reference to ContactPools of type 'id'.
Parameters
id ContactType::Id of pools container you want to access.
Returns
The requested reference.
Definition at line 117 of file Epidemiologic.h.
References m_pool_index.
Referenced by operator==().
template<stride::ContactType::Id T> const stride::util::SegmentedVector<stride::ContactPool*>& geopop::Epidemiologic::CRefPools () const inline
Templated version of for use when the type id is fixed.
Template Parameters
T ContactType::Id of pools container you want to access.
Returns
The requested reference.
Definition at line 126 of file Epidemiologic.h.
References m_pool_index.
Referenced by GenerateEpiOutput(), GetMemberCount(), and operator==().
stride::util::SegmentedVector<stride::ContactPool*>& geopop::Epidemiologic::RefPools (stride::ContactType::Id id) inline
Access through reference to ContactPools of type 'id'.
Parameters
id ContactType::Id of pools container you want to access.
Returns
The requested reference.
Definition at line 134 of file Epidemiologic.h.
References m_pool_index.
template<stride::ContactType::Id T> stride::util::SegmentedVector<stride::ContactPool*>& geopop::Epidemiologic::RefPools () inline
Templated version of for use when the type id is fixed.
Template Parameters
T ContactType::Id of pools container you want to access.
Returns
The requested reference.
Definition at line 143 of file Epidemiologic.h.
References m_pool_index.
void geopop::Epidemiologic::RegisterPool (stride::ContactPool * p, stride::ContactType::Id typeId) inline
Register a ContactPool pointer in this Epidemiologic's pool system.
Prior to this the pool should have been created in Population's pool system.
Definition at line 150 of file Epidemiologic.h.
References m_pool_index.
template<stride::ContactType::Id T> void geopop::Epidemiologic::RegisterPool (stride::ContactPool * p) inline
Templated version of .
Definition at line 157 of file Epidemiologic.h.
References m_pool_index.
const std::vector<std::pair<Epidemiologic*, double> >& geopop::Epidemiologic::CRefIncomingCommutes () const inline
References incoming commute Epidemiologics + fraction of commutes to that Epidemiologic.
Definition at line 164 of file Epidemiologic.h.
References m_inCommutes.
Referenced by operator==().
const std::vector<std::pair<Epidemiologic*, double> >& geopop::Epidemiologic::CRefOutgoingCommutes () const inline
References outgoing commute Epidemiologics + fraction of commutes to that Epidemiologic.
Definition at line 167 of file Epidemiologic.h.
References m_outCommutes.
Referenced by operator==().
Member Data Documentation
unsigned int geopop::Epidemiologic::m_pop_count private
Population count (number of individuals) at this Epidemiologic.
Definition at line 170 of file Epidemiologic.h.
Referenced by GetOutgoingCommuteCount(), GetPopCount(), and SetPopCount().
double geopop::Epidemiologic::m_pop_fraction private
Fraction of whole population at this Epidemiologic.
Definition at line 171 of file Epidemiologic.h.
Referenced by GetPopFraction(), SetPopCount(), and SetPopFraction().
Location<Epidemiologic>* geopop::Epidemiologic::m_location private
Link to the location.
Definition at line 172 of file Epidemiologic.h.
Referenced by GetID(), and GetLocation().
unsigned int geopop::Epidemiologic::m_household_type private
Household type.
Definition at line 173 of file Epidemiologic.h.
Referenced by GetHouseHoldType(), and SetHouseHoldType().
double geopop::Epidemiologic::m_young_old_fraction private
Young/Old fraction (ratio between 15-24y and 55-64y old persons).
Definition at line 174 of file Epidemiologic.h.
Referenced by GetYoungOldFraction(), and SetYoungOldFraction().
std::vector<std::pair<Epidemiologic*, double> > geopop::Epidemiologic::m_inCommutes private
Incomming commutes stored as pair of Epidemiologic and fraction of population at that Epidemiologic.
Outgoing commutes stored as pair of Epidemiologic and fraction of population to this this Epidemiologic.
Definition at line 177 of file Epidemiologic.h.
Referenced by AddIncomingCommute(), CRefIncomingCommutes(), and GetIncomingCommuteCount().
std::vector<std::pair<Epidemiologic*, double> > geopop::Epidemiologic::m_outCommutes private
The system holding pointers to the contactpools (for each type id) at this Epidemiologic.
Definition at line 180 of file Epidemiologic.h.
Referenced by AddOutgoingCommute(), CRefOutgoingCommutes(), and GetOutgoingCommuteCount().
stride::ContactType::IdSubscriptArray<stride::util::SegmentedVector<stride::ContactPool*> > geopop::Epidemiologic::m_pool_index private
Definition at line 183 of file Epidemiologic.h.
Referenced by CRefPools(), RefPools(), and RegisterPool().
The documentation for this class was generated from the following files:
Epidemiologic.h
Epidemiologic.cpp