Stride Reference Manual: proto::EpiOutput_Day_Location_Coordinate Class Reference
proto::EpiOutput_Day_Location_Coordinate Class Reference final
#include <epioutput.pb.h>
Public Member Functions
EpiOutput_Day_Location_Coordinate ()
virtual ~EpiOutput_Day_Location_Coordinate ()
EpiOutput_Day_Location_Coordinate (const EpiOutput_Day_Location_Coordinate &from)
EpiOutput_Day_Location_Coordinate & operator= (const EpiOutput_Day_Location_Coordinate &from)
void Swap (EpiOutput_Day_Location_Coordinate *other)
EpiOutput_Day_Location_Coordinate * New () const final
EpiOutput_Day_Location_Coordinate * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const EpiOutput_Day_Location_Coordinate &from)
void MergeFrom (const EpiOutput_Day_Location_Coordinate &from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_longitude ()
double longitude () const
void set_longitude (double value)
void clear_latitude ()
double latitude () const
void set_latitude (double value)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const EpiOutput_Day_Location_Coordinate & default_instance ()
static void InitAsDefaultInstance ()
static const EpiOutput_Day_Location_Coordinate * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kLongitudeFieldNumber = 1
static const int kLatitudeFieldNumber = 2
Private Member Functions
void SharedCtor ()
void SharedDtor ()
void SetCachedSize (int size) const final
void InternalSwap (EpiOutput_Day_Location_Coordinate *other)
inline::google::protobuf::Arena * GetArenaNoVirtual () const
void * MaybeArenaPtr () const
Private Attributes
::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_
double longitude_
double latitude_
mutable::google::protobuf::internal::CachedSize _cached_size_
Friends
struct ::TableStruct_epioutput_2eproto
void swap (EpiOutput_Day_Location_Coordinate &a, EpiOutput_Day_Location_Coordinate &b)
Detailed Description
Definition at line 85 of file epioutput.pb.h.
Constructor & Destructor Documentation
proto::EpiOutput_Day_Location_Coordinate::EpiOutput_Day_Location_Coordinate ()
virtual proto::EpiOutput_Day_Location_Coordinate::~EpiOutput_Day_Location_Coordinate () virtual
proto::EpiOutput_Day_Location_Coordinate::EpiOutput_Day_Location_Coordinate (const EpiOutput_Day_Location_Coordinate & from)
Member Function Documentation
EpiOutput_Day_Location_Coordinate& proto::EpiOutput_Day_Location_Coordinate::operator= (const EpiOutput_Day_Location_Coordinate & from) inline
Definition at line 93 of file epioutput.pb.h.
References GetArenaNoVirtual().
static const ::google::protobuf::Descriptor* proto::EpiOutput_Day_Location_Coordinate::descriptor () inline static
Definition at line 112 of file epioutput.pb.h.
static const EpiOutput_Day_Location_Coordinate& proto::EpiOutput_Day_Location_Coordinate::default_instance () static
static void proto::EpiOutput_Day_Location_Coordinate::InitAsDefaultInstance () static
static const EpiOutput_Day_Location_Coordinate* proto::EpiOutput_Day_Location_Coordinate::internal_default_instance () inline static
Definition at line 118 of file epioutput.pb.h.
References proto::_EpiOutput_Day_Location_Coordinate_default_instance_.
void proto::EpiOutput_Day_Location_Coordinate::Swap (EpiOutput_Day_Location_Coordinate * other)
EpiOutput_Day_Location_Coordinate* proto::EpiOutput_Day_Location_Coordinate::New () const inline final
Definition at line 132 of file epioutput.pb.h.
EpiOutput_Day_Location_Coordinate* proto::EpiOutput_Day_Location_Coordinate::New (::google::protobuf::Arena * arena) const inline final
Definition at line 136 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location_Coordinate::CopyFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day_Location_Coordinate::MergeFrom (const ::google::protobuf::Message & from) final
void proto::EpiOutput_Day_Location_Coordinate::CopyFrom (const EpiOutput_Day_Location_Coordinate & from)
void proto::EpiOutput_Day_Location_Coordinate::MergeFrom (const EpiOutput_Day_Location_Coordinate & from)
PROTOBUF_ATTRIBUTE_REINITIALIZES void proto::EpiOutput_Day_Location_Coordinate::Clear () final
Referenced by proto::EpiOutput_Day_Location::clear_agebrackets().
bool proto::EpiOutput_Day_Location_Coordinate::IsInitialized () const final
size_t proto::EpiOutput_Day_Location_Coordinate::ByteSizeLong () const final
bool proto::EpiOutput_Day_Location_Coordinate::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
void proto::EpiOutput_Day_Location_Coordinate::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
::google::protobuf::uint8* proto::EpiOutput_Day_Location_Coordinate::InternalSerializeWithCachedSizesToArray (::google::protobuf::uint8 * target) const final
int proto::EpiOutput_Day_Location_Coordinate::GetCachedSize () const inline final
Definition at line 158 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location_Coordinate::SharedCtor () private
void proto::EpiOutput_Day_Location_Coordinate::SharedDtor () private
void proto::EpiOutput_Day_Location_Coordinate::SetCachedSize (int size) const final private
void proto::EpiOutput_Day_Location_Coordinate::InternalSwap (EpiOutput_Day_Location_Coordinate * other) private
inline ::google::protobuf::Arena* proto::EpiOutput_Day_Location_Coordinate::GetArenaNoVirtual () const inline private
Definition at line 166 of file epioutput.pb.h.
Referenced by operator=().
void* proto::EpiOutput_Day_Location_Coordinate::MaybeArenaPtr () const inline private
Definition at line 169 of file epioutput.pb.h.
::google::protobuf::Metadata proto::EpiOutput_Day_Location_Coordinate::GetMetadata () const final
void proto::EpiOutput_Day_Location_Coordinate::clear_longitude () inline
Definition at line 890 of file epioutput.pb.h.
double proto::EpiOutput_Day_Location_Coordinate::longitude () const inline
Definition at line 893 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location_Coordinate::set_longitude (double value) inline
Definition at line 897 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location_Coordinate::clear_latitude () inline
Definition at line 904 of file epioutput.pb.h.
double proto::EpiOutput_Day_Location_Coordinate::latitude () const inline
Definition at line 907 of file epioutput.pb.h.
void proto::EpiOutput_Day_Location_Coordinate::set_latitude (double value) inline
Definition at line 911 of file epioutput.pb.h.
Friends And Related Function Documentation
friend struct ::TableStruct_epioutput_2eproto friend
Definition at line 200 of file epioutput.pb.h.
void swap (EpiOutput_Day_Location_Coordinate & a, EpiOutput_Day_Location_Coordinate & b) friend
Definition at line 126 of file epioutput.pb.h.
Member Data Documentation
constexpr int proto::EpiOutput_Day_Location_Coordinate::kIndexInFileMessages static
Initial value:
=
    0
Definition at line 122 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location_Coordinate::kLongitudeFieldNumber = 1 static
Definition at line 182 of file epioutput.pb.h.
const int proto::EpiOutput_Day_Location_Coordinate::kLatitudeFieldNumber = 2 static
Definition at line 188 of file epioutput.pb.h.
::google::protobuf::internal::InternalMetadataWithArena proto::EpiOutput_Day_Location_Coordinate::_internal_metadata_ private
Definition at line 194 of file epioutput.pb.h.
double proto::EpiOutput_Day_Location_Coordinate::longitude_ private
Definition at line 197 of file epioutput.pb.h.
double proto::EpiOutput_Day_Location_Coordinate::latitude_ private
Definition at line 198 of file epioutput.pb.h.
mutable ::google::protobuf::internal::CachedSize proto::EpiOutput_Day_Location_Coordinate::_cached_size_ private
Definition at line 199 of file epioutput.pb.h.
The documentation for this class was generated from the following file:
epioutput.pb.h