Stride Reference Manual: geopop::EpiOutputProtoWriter Class Reference
geopop::EpiOutputProtoWriter Class Reference
Writes a GeoGrid epi-output to a protobuf file.
#include <EpiOutputProtoWriter.h>
Public Member Functions
EpiOutputProtoWriter (const std::string &filename="")
Construct the EpiOutputJSONWriter.
void Write () override
Write the provided GeoGrid epi-output to the provided JSON file. (If given)
void Write (std::ostream &stream)
Write the provided GeoGrid epi-output to the provided ostream in JSON format. (Only for test purposes)
void Update (GeoGrid< Epidemiologic > &geoGrid, unsigned int day) override
Write the epi-output of the GeoGrid to the right data format.
Public Member Functions inherited from geopop::EpiOutputWriter
virtual ~EpiOutputWriter ()=default
Deconstruct the Writer.
Private Attributes
proto::EpiOutput m_output
protobuf to be written to a file
std::ofstream m_fstream
The file stream.
Detailed Description
Writes a GeoGrid epi-output to a protobuf file.
Definition at line 37 of file EpiOutputProtoWriter.h.
Constructor & Destructor Documentation
geopop::EpiOutputProtoWriter::EpiOutputProtoWriter (const std::string & filename = "") explicit
Construct the EpiOutputJSONWriter.
Definition at line 33 of file EpiOutputProtoWriter.cpp.
References m_fstream.
Member Function Documentation
void geopop::EpiOutputProtoWriter::Write () override virtual
Write the provided GeoGrid epi-output to the provided JSON file. (If given)
Implements geopop::EpiOutputWriter.
Definition at line 39 of file EpiOutputProtoWriter.cpp.
References m_fstream.
void geopop::EpiOutputProtoWriter::Write (std::ostream & stream)
Write the provided GeoGrid epi-output to the provided ostream in JSON format. (Only for test purposes)
Definition at line 45 of file EpiOutputProtoWriter.cpp.
References m_output.
void geopop::EpiOutputProtoWriter::Update (GeoGrid< Epidemiologic > & geoGrid, unsigned int day) override virtual
Write the epi-output of the GeoGrid to the right data format.
Implements geopop::EpiOutputWriter.
Definition at line 53 of file EpiOutputProtoWriter.cpp.
References proto::EpiOutput::add_days(), stride::ageBrackets, stride::healthStatuses, m_output, proto::EpiOutput_Day::set_day(), and geopop::GeoGrid< LocationContent >::size().
Member Data Documentation
proto::EpiOutput geopop::EpiOutputProtoWriter::m_output private
protobuf to be written to a file
Definition at line 53 of file EpiOutputProtoWriter.h.
Referenced by Update(), and Write().
std::ofstream geopop::EpiOutputProtoWriter::m_fstream private
The file stream.
Definition at line 54 of file EpiOutputProtoWriter.h.
Referenced by EpiOutputProtoWriter(), and Write().
The documentation for this class was generated from the following files:
EpiOutputProtoWriter.h
EpiOutputProtoWriter.cpp