Stride Reference Manual: geopop Namespace Reference
geopop Namespace Reference
Namespace for the geographic and demograhic classes.
Namespaces
geogrid_detail
kd
Classes
struct AABBox
AxisAlignedBoundingBox (hyperrectangle defined by lower and upper bound for every dimension).
class BoxPolicy
GeoAggregator Policy that aggregates over an axis aligned bounding box.
class Collector
Aggregates into a vector that must should remain alive for the usage duration of the Collector.
class CommutesCSVReader
Create a Reader that fills a GeoGrid with the commute info from CSV file.
class CommutesReader
Create an abstract Reader that fills a GeoGrid with the commute info from file.
class DistributionReader
Retrieves the reference distribution profiles from file.
class Epidemiologic
Epidemiologic for use within the GeoGrid, contains index to ContactPools and commutes.
class EpiOutputHDF5Writer
Writes a GeoGrid epi-output to a HDF5 file.
class EpiOutputJSONWriter
Writes a GeoGrid epi-output to a JSON file.
class EpiOutputProtoWriter
Writes a GeoGrid epi-output to a protobuf file.
class EpiOutputWriter
An interface for writing the epi-output of a GeoGrid to a file, can be implemented with multiple file types.
class EpiOutputWriterFactory
Factory creates the correct implementation of a EpiOutputWriter based on the filename extension.
class Generator
Generator uses geo & pop data to construct ContactPools in the GeoGrid.
class GeoAggregator
A GeoAggregator can either be instantiated with a functor, or be called with one every time.
class GeoAggregator< Policy >
A GeoAggregator that has to be called with a functor.
class GeoAggregator< Policy, F >
A GeoAggregator constructed with a functor.
class GeoGrid
A Geographic grid of simulation region contains Locations that in turn contain an index to the ContactPools situated at that Location.
class GeoGridConfig
Configuration data mostly for generating a population, but also for computing the required number of schools, workplaces, communities etc.
class GeoGridFileReader
An abstract base class for creating a GeoGrid that was read from a file located at inputFilePath, can be implemented using multiple file types (hdf5 is currently implemented)
class GeoGridFileWriter
An interface for writing the GeoGrid to a filelocated at inputFilePath, can be implemented with multiple file types.
class GeoGridHDF5Reader
An implementation of the GeoGridFileReader using HDF5.
class GeoGridHDF5Writer
An implementation of the GeoGridFileWriter using HDF5 This class is used to write a GeoGrid to an HDF5 file.
class GeoGridJSONReader
An implementation of the GeoGridReader using JSON.
class GeoGridJSONWriter
Writes a GeoGrid to a JSON file.
class GeoGridProtoReader
An implementation of the GeoGridReader using Protocol Buffers.
class GeoGridProtoWriter
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
class GeoGridReader
An abstract base class for creating a GeoGrid that was read from a file, can be implemented using multiple file types (proto, hdf5 and json are currently implemented)
class GeoGridReaderFactory
A Factory for creating the correct implementation of a GeoGridReader based on the filename extension.
class GeoGridStreamReader
An abstract base class for creating a GeoGrid that was read from a stream, can be implemented using multiple file types (proto and json are currently implemented)
class GeoGridStreamWriter
An interface for writing the GeoGrid to an output stream, can be implemented with multiple file types.
class GeoGridWriter
An interface for writing the GeoGrid.
class GeoGridWriterFactory
Factory creates the correct implementation of a GeoGridWriter based on the filename extension.
class HouseholdCSVReader
Creates a Reader that retrieves the different Household profiles from a given CSV file.
class HouseholdJSONReader
Creates a Reader that retrieves the different Household profiles from a given JSON file.
class HouseholdReader
Retrieves the reference Household profiles from file.
class KdTree
A k-d tree: a k-dimensional generalization of binary search trees This data structure allows for efficient lookup of points and range queries with an Axis-Aligned Bounding Box (when balanced).
class Location
Location for use within the GeoGrid, contains Coordinate and meta data of that coordinate.
class LocationsCSVReader
Create a Reader that fills a GeoGrid with the Location data found in a CSV input stream.
class LocationsReader
Create an abstract Reader which fills a GeoGrid with the cities found in file.
class PolygonPolicy
A GeoAggregator Policy that aggregates over a (clockwise) polygon.
struct PopulationInfo
class Populator
Populator uses geo & pop data to populate ContactPools in the GeoGrid.
class RadiusPolicy
GeoAggregator Policy that aggregates locations within a radius (in km) of a center point.
class ReaderFactory
A Factory for creating the correct implementation of the different Readers which parse the information needed to construct a GeoGrid, based on the file extension.
struct ReferenceHouseHold
class WorkplaceCSVReader
Creates a Reader that retrieves the different distributions for workplaces from a given CSV file.
Typedefs
using Coordinate = boost::geometry::model::point< double, 2, boost::geometry::cs::geographic< boost::geometry::degree >>
using DaycareGenerator = Generator< stride::ContactType::Id::Daycare >
using PreSchoolGenerator = Generator< stride::ContactType::Id::PreSchool >
using K12SchoolGenerator = Generator< stride::ContactType::Id::K12School >
using CollegeGenerator = Generator< stride::ContactType::Id::College >
using WorkplaceGenerator = Generator< stride::ContactType::Id::Workplace >
using HouseholdGenerator = Generator< stride::ContactType::Id::Household >
using PrimaryCommunityGenerator = Generator< stride::ContactType::Id::PrimaryCommunity >
using SecondaryCommunityGenerator = Generator< stride::ContactType::Id::SecondaryCommunity >
using GeoGridKdTree = KdTree< geogrid_detail::KdTree2DPoint >
using json = nlohmann::json
using DaycarePopulator = Populator< stride::ContactType::Id::Daycare >
using PreSchoolPopulator = Populator< stride::ContactType::Id::PreSchool >
using K12SchoolPopulator = Populator< stride::ContactType::Id::K12School >
using CollegePopulator = Populator< stride::ContactType::Id::College >
using WorkplacePopulator = Populator< stride::ContactType::Id::Workplace >
using HouseholdPopulator = Populator< stride::ContactType::Id::Household >
using PrimaryCommunityPopulator = Populator< stride::ContactType::Id::PrimaryCommunity >
using SecondaryCommunityPopulator = Populator< stride::ContactType::Id::SecondaryCommunity >
Functions
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type>
Collector< InsertIter, T > MakeCollector (const InsertIter &ins)
Build a Collector, useful for type inference.
ostream & operator<< (ostream &out, const GeoGridConfig &config)
Detailed Description
Namespace for the geographic and demograhic classes.
Typedef Documentation
using geopop::Coordinate = typedef boost::geometry::model::point<double, 2, boost::geometry::cs::geographic<boost::geometry::degree>>
Definition at line 23 of file Coordinate.h.
using geopop::DaycareGenerator = typedef Generator<stride::ContactType::Id::Daycare>
Definition at line 108 of file Generator.h.
using geopop::PreSchoolGenerator = typedef Generator<stride::ContactType::Id::PreSchool>
Definition at line 109 of file Generator.h.
using geopop::K12SchoolGenerator = typedef Generator<stride::ContactType::Id::K12School>
Definition at line 110 of file Generator.h.
using geopop::CollegeGenerator = typedef Generator<stride::ContactType::Id::College>
Definition at line 111 of file Generator.h.
using geopop::WorkplaceGenerator = typedef Generator<stride::ContactType::Id::Workplace>
Definition at line 112 of file Generator.h.
using geopop::HouseholdGenerator = typedef Generator<stride::ContactType::Id::Household>
Definition at line 113 of file Generator.h.
using geopop::PrimaryCommunityGenerator = typedef Generator<stride::ContactType::Id::PrimaryCommunity>
Definition at line 114 of file Generator.h.
using geopop::SecondaryCommunityGenerator = typedef Generator<stride::ContactType::Id::SecondaryCommunity>
Definition at line 115 of file Generator.h.
using geopop::GeoGridKdTree = typedef KdTree<geogrid_detail::KdTree2DPoint>
Definition at line 25 of file GeoGridKdTree.h.
typedef nlohmann::json geopop::json
Definition at line 32 of file EpiOutputJSONWriter.cpp.
using geopop::DaycarePopulator = typedef Populator<stride::ContactType::Id::Daycare>
Definition at line 94 of file Populator.h.
using geopop::PreSchoolPopulator = typedef Populator<stride::ContactType::Id::PreSchool>
Definition at line 95 of file Populator.h.
using geopop::K12SchoolPopulator = typedef Populator<stride::ContactType::Id::K12School>
Definition at line 96 of file Populator.h.
using geopop::CollegePopulator = typedef Populator<stride::ContactType::Id::College>
Definition at line 97 of file Populator.h.
using geopop::WorkplacePopulator = typedef Populator<stride::ContactType::Id::Workplace>
Definition at line 98 of file Populator.h.
using geopop::HouseholdPopulator = typedef Populator<stride::ContactType::Id::Household>
Definition at line 99 of file Populator.h.
using geopop::PrimaryCommunityPopulator = typedef Populator<stride::ContactType::Id::PrimaryCommunity>
Definition at line 100 of file Populator.h.
using geopop::SecondaryCommunityPopulator = typedef Populator<stride::ContactType::Id::SecondaryCommunity>
Definition at line 101 of file Populator.h.
Function Documentation
template<typename InsertIter , typename T = typename InsertIter::container_type::value_type> Collector<InsertIter, T> geopop::MakeCollector (const InsertIter & ins)
Build a Collector, useful for type inference.
Definition at line 60 of file GeoAggregator.h.
Referenced by geopop::GeoGrid< LocationContent >::LocationsInBox(), and geopop::GeoGrid< LocationContent >::LocationsInRadius().
ostream& geopop::operator<< (ostream & out, const GeoGridConfig & config)
Definition at line 230 of file GeoGridConfig.cpp.
References geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::fraction_workplace_commuters, geopop::GeoGridConfig::info, stride::util::intToDottedString(), geopop::GeoGridConfig::param, geopop::GeoGridConfig::participation_college, geopop::GeoGridConfig::participation_daycare, geopop::GeoGridConfig::participation_preschool, geopop::GeoGridConfig::participation_workplace, geopop::GeoGridConfig::pop_size, geopop::PopulationInfo::popcount_college, geopop::PopulationInfo::popcount_daycare, geopop::PopulationInfo::popcount_k12school, geopop::PopulationInfo::popcount_preschool, and geopop::PopulationInfo::popcount_workplace.