Stride Reference Manual: visualization::EpiOutputHDF5Reader Class Reference
visualization::EpiOutputHDF5Reader Class Reference
An implementation of the EpiOutputReader using HDF5.
#include <EpiOutputHDF5Reader.h>
Public Member Functions
EpiOutputHDF5Reader (const std::string &filename, geopop::GeoGrid< EpiOutput > *epiOutput)
Construct the EpiOutputHDF5Reader with the istream which contains the HDF5.
EpiOutputHDF5Reader (const EpiOutputHDF5Reader &)=delete
No copy constructor.
EpiOutputHDF5Reader operator= (const EpiOutputHDF5Reader &)=delete
No copy assignement.
void Read () override
Actually perform the read and return the EpiOutput.
Public Member Functions inherited from visualization::EpiOutputReader
EpiOutputReader (geopop::GeoGrid< EpiOutput > *epiOutput)
Parametrized constructor.
EpiOutputReader (const EpiOutputReader &)=delete
No copy constructor.
EpiOutputReader & operator= (const EpiOutputReader &)=delete
No copy assignement.
virtual ~EpiOutputReader ()=default
Default destructor.
Private Member Functions
void ReadDay (const H5::Group &day, geopop::GeoGrid< EpiOutput > &grid)
Private Attributes
H5::H5File m_input
HDF5 file.
Additional Inherited Members
Protected Attributes inherited from visualization::EpiOutputReader
geopop::GeoGrid< EpiOutput > * m_epiOutput
Resulting epi-output.
Detailed Description
An implementation of the EpiOutputReader using HDF5.
This class is used to read a epi-output from a HDF5 file.
Definition at line 31 of file EpiOutputHDF5Reader.h.
Constructor & Destructor Documentation
visualization::EpiOutputHDF5Reader::EpiOutputHDF5Reader (const std::string & filename, geopop::GeoGrid< EpiOutput > * epiOutput)
Construct the EpiOutputHDF5Reader with the istream which contains the HDF5.
Definition at line 33 of file EpiOutputHDF5Reader.cpp.
References m_input.
visualization::EpiOutputHDF5Reader::EpiOutputHDF5Reader (const EpiOutputHDF5Reader &) delete
No copy constructor.
Member Function Documentation
EpiOutputHDF5Reader visualization::EpiOutputHDF5Reader::operator= (const EpiOutputHDF5Reader &) delete
No copy assignement.
void visualization::EpiOutputHDF5Reader::Read () override virtual
Actually perform the read and return the EpiOutput.
Implements visualization::EpiOutputReader.
Definition at line 41 of file EpiOutputHDF5Reader.cpp.
References visualization::EpiOutputReader::m_epiOutput, m_input, H5Utils::ReadAttribute(), and ReadDay().
void visualization::EpiOutputHDF5Reader::ReadDay (const H5::Group & day, geopop::GeoGrid< EpiOutput > & grid) private
Definition at line 57 of file EpiOutputHDF5Reader.cpp.
References geopop::GeoGrid< LocationContent >::AddLocation(), stride::ageBrackets, H5Utils::GetCompoundType< H5EpiOutput >(), stride::healthStatuses, and H5Utils::ReadAttribute().
Referenced by Read().
Member Data Documentation
H5::H5File visualization::EpiOutputHDF5Reader::m_input private
HDF5 file.
Definition at line 48 of file EpiOutputHDF5Reader.h.
Referenced by EpiOutputHDF5Reader(), and Read().
The documentation for this class was generated from the following files:
EpiOutputHDF5Reader.h
EpiOutputHDF5Reader.cpp