Stride Reference Manual: geopop::GeoGridHDF5Reader Class Reference
geopop::GeoGridHDF5Reader Class Reference
An implementation of the GeoGridFileReader using HDF5.
#include <GeoGridHDF5Reader.h>
Public Member Functions
GeoGridHDF5Reader (std::string inputFilePath, stride::Population *pop)
Construct the GeoGridHDF5Reader with the string which contains the location of the input file.
GeoGridHDF5Reader (const GeoGridHDF5Reader &)=delete
No copy constructor.
GeoGridHDF5Reader operator= (const GeoGridHDF5Reader &)=delete
No copy assignement.
void Read () override
Actually perform the read.
Public Member Functions inherited from geopop::GeoGridFileReader
GeoGridFileReader (std::string inputFilePath, stride::Population *pop)
Parametrized constructor.
GeoGridFileReader (const GeoGridFileReader &)=delete
No copy constructor.
GeoGridFileReader & operator= (const GeoGridFileReader &)=delete
No copy assignment.
~GeoGridFileReader () override=default
Default destructor.
Public Member Functions inherited from geopop::GeoGridReader
GeoGridReader (stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
void ReadPeople (const H5::DataSet &people)
People.
void ReadPerson (const H5Utils::H5Person &person)
void ReadLocations (const H5::Group &locations, GeoGrid< Epidemiologic > &grid)
Locations.
void ReadLocation (const H5::Group &location, GeoGrid< Epidemiologic > &grid)
void ReadContactPool (const H5::DataSet &pool, const std::shared_ptr< Location< Epidemiologic >> &location)
Additional Inherited Members
Protected Member Functions inherited from geopop::GeoGridReader
void AddCommutes (GeoGrid< Epidemiologic > &geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from geopop::GeoGridFileReader
std::string m_inputFilePath
File to read.
Protected Attributes inherited from geopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
< Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
stride::Population * m_population
Population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridFileReader using HDF5.
This class is used to read a GeoGrid from an HDF5 file.
Definition at line 32 of file GeoGridHDF5Reader.h.
Constructor & Destructor Documentation
geopop::GeoGridHDF5Reader::GeoGridHDF5Reader (std::string inputFilePath, stride::Population * pop)
Construct the GeoGridHDF5Reader with the string which contains the location of the input file.
Definition at line 36 of file GeoGridHDF5Reader.cpp.
geopop::GeoGridHDF5Reader::GeoGridHDF5Reader (const GeoGridHDF5Reader &) delete
No copy constructor.
Member Function Documentation
GeoGridHDF5Reader geopop::GeoGridHDF5Reader::operator= (const GeoGridHDF5Reader &) delete
No copy assignement.
void geopop::GeoGridHDF5Reader::Read () override virtual
Actually perform the read.
Open file
Read people dataset
Read locations group
Implements geopop::GeoGridFileReader.
Definition at line 41 of file GeoGridHDF5Reader.cpp.
References geopop::GeoGridReader::AddCommutes(), geopop::GeoGridReader::m_commutes, geopop::GeoGridFileReader::m_inputFilePath, geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, ReadLocations(), ReadPeople(), and stride::Population::RefGeoGrid().
void geopop::GeoGridHDF5Reader::ReadPeople (const H5::DataSet & people) private
People.
Definition at line 73 of file GeoGridHDF5Reader.cpp.
References H5Utils::GetCompoundType< H5Person >(), H5Utils::ReadAttribute(), and ReadPerson().
Referenced by Read().
void geopop::GeoGridHDF5Reader::ReadPerson (const H5Utils::H5Person & person) private
Definition at line 88 of file GeoGridHDF5Reader.cpp.
References H5Utils::H5Person::age, H5Utils::H5Person::College, stride::Population::CreatePerson(), H5Utils::H5Person::Daycare, H5Utils::H5Person::Household, H5Utils::H5Person::id, H5Utils::H5Person::K12School, geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, H5Utils::H5Person::PreSchool, H5Utils::H5Person::PrimaryCommunity, H5Utils::H5Person::SecondaryCommunity, and H5Utils::H5Person::Workplace.
Referenced by ReadPeople().
void geopop::GeoGridHDF5Reader::ReadLocations (const H5::Group & locations, GeoGrid< Epidemiologic > & grid) private
Locations.
Definition at line 97 of file GeoGridHDF5Reader.cpp.
References H5Utils::ReadAttribute(), and ReadLocation().
Referenced by Read().
void geopop::GeoGridHDF5Reader::ReadLocation (const H5::Group & location, GeoGrid< Epidemiologic > & grid) private
Location
Contact Pools
Commutes
Definition at line 110 of file GeoGridHDF5Reader.cpp.
References geopop::GeoGrid< LocationContent >::AddLocation(), H5Utils::GetCompoundType< H5Commute >(), geopop::GeoGridReader::m_commutes, H5Utils::ReadAttribute(), and ReadContactPool().
Referenced by ReadLocations().
void geopop::GeoGridHDF5Reader::ReadContactPool (const H5::DataSet & pool, const std::shared_ptr< Location< Epidemiologic >> & location) private
Definition at line 158 of file GeoGridHDF5Reader.cpp.
References stride::ContactPoolSys::CreateContactPool(), H5Utils::GetCompoundType< H5PoolPerson >(), geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, H5Utils::ReadAttribute(), and stride::Population::RefPoolSys().
Referenced by ReadLocation().
The documentation for this class was generated from the following files:
GeoGridHDF5Reader.h
GeoGridHDF5Reader.cpp