Stride Reference Manual: geopop::GeoGrid< LocationContent > Class Template Reference
geopop::GeoGrid< LocationContent > Class Template Reference
A Geographic grid of simulation region contains Locations that in turn contain an index to the ContactPools situated at that Location.
#include <Generator.h>
Public Types
using iterator = typename std::vector< std::shared_ptr< Location< LocationContent >>>::iterator
using const_iterator = typename std::vector< std::shared_ptr< Location< LocationContent >>>::const_iterator
Public Member Functions
GeoGrid (stride::Population *population)
GeoGrid and associated Population.
GeoGrid (const GeoGrid &)=delete
No copy constructor.
GeoGrid operator= (const GeoGrid &)=delete
No copy assignment.
void AddLocation (std::shared_ptr< Location< LocationContent >> location)
Adds a location to this GeoGrid.
void Finalize ()
Disables the addLocation method and builds the kdtree.
std::shared_ptr< Location< LocationContent > > GetById (unsigned int id) const
Gets a Location by Id and check if the Id exists.
stride::Population * GetPopulation () const
Get the Population associated with this GeoGrid.
std::vector< const Location< LocationContent > * > LocationsInRadius (const Location< LocationContent > &start, double radius) const
Search for locations in radius (in km) around start.
template<typename = std::enable_if<std::is_same<LocationContent, Epidemiologic>::value>>
std::vector< stride::ContactPool * > GetNearbyPools (stride::ContactType::Id id, const Location< Epidemiologic > &start, double startRadius=10.0) const
Find contactpools in startRadius (in km) around start and, if none are found, double the radius and search again until the radius gets infinite.
std::set< const Location< LocationContent > * > LocationsInBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
std::set< const Location< LocationContent > * > LocationsInBox (Location< LocationContent > *loc1, Location< LocationContent > *loc2) const
Gets the location in a rectangle defined by the two Locations.
std::vector< Location< LocationContent > * > TopK (size_t k) const
Gets the K biggest (in population count) locations of this GeoGrid.
template<typename Policy , typename F >
GeoAggregator< Policy, F > BuildAggregator (F functor, typename Policy::Args &&args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
template<typename Policy >
GeoAggregator< Policy > BuildAggregator (typename Policy::Args &&args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
iterator begin ()
Iterator to first Location.
iterator end ()
Iterator to the end of the Location storage.
const_iterator cbegin () const
Const Iterator to first Location.
const_iterator cend () const
Const iterator to the end of the Location storage.
std::shared_ptr< Location< LocationContent > > & operator[] (size_t index)
Gets a Location by index, doesn't performs a range check.
const std::shared_ptr< Location< LocationContent > > & operator[] (size_t index) const
Gets a Location by index, doesn't performs a range check.
size_t size () const
Gets current size of Location storage.
Private Member Functions
void CheckFinalized (const std::string &functionName) const
< Checks whether the GeoGrid is finalized i.e. certain operations can(not) be used.
Private Attributes
std::vector< std::shared_ptr< Location< LocationContent > > > m_locations
< Container for Locations in GeoGrid.
std::unordered_map< unsigned int, unsigned int > m_id_to_index
Stores pointer to Popluation, but does not take ownership.
stride::Population * m_population
Is the GeoGrid finalized (ready for use) yet?
bool m_finalized
Internal KdTree for quick spatial lookup.
GeoGridKdTree m_tree
Detailed Description
template<class LocationContent>
class geopop::GeoGrid< LocationContent >
A Geographic grid of simulation region contains Locations that in turn contain an index to the ContactPools situated at that Location.
Definition at line 31 of file Generator.h.
Member Typedef Documentation
template<class LocationContent> using geopop::GeoGrid< LocationContent >::iterator = typename std::vector<std::shared_ptr<Location<LocationContent>>>::iterator
Definition at line 123 of file GeoGrid.h.
template<class LocationContent> using geopop::GeoGrid< LocationContent >::const_iterator = typename std::vector<std::shared_ptr<Location<LocationContent>>>::const_iterator
Definition at line 124 of file GeoGrid.h.
Constructor & Destructor Documentation
template<class LocationContent > geopop::GeoGrid< LocationContent >::GeoGrid (stride::Population * population) explicit
GeoGrid and associated Population.
Definition at line 35 of file GeoGrid.cpp.
template<class LocationContent> geopop::GeoGrid< LocationContent >::GeoGrid (const GeoGrid< LocationContent > &) delete
No copy constructor.
Member Function Documentation
template<class LocationContent> GeoGrid geopop::GeoGrid< LocationContent >::operator= (const GeoGrid< LocationContent > &) delete
No copy assignment.
template<class LocationContent> void geopop::GeoGrid< LocationContent >::AddLocation (std::shared_ptr< Location< LocationContent >> location)
Adds a location to this GeoGrid.
Definition at line 41 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::m_finalized, geopop::GeoGrid< LocationContent >::m_id_to_index, and geopop::GeoGrid< LocationContent >::m_locations.
Referenced by geopop::LocationsCSVReader::FillGeoGrid(), visualization::EpiOutputJSONReader::Read(), visualization::EpiOutputHDF5Reader::ReadDay(), and geopop::GeoGridHDF5Reader::ReadLocation().
template<class LocationContent > void geopop::GeoGrid< LocationContent >::Finalize ()
Disables the addLocation method and builds the kdtree.
Definition at line 73 of file GeoGrid.cpp.
References geopop::KdTree< geogrid_detail::KdTree2DPoint >::Build(), geopop::GeoGrid< LocationContent >::m_finalized, geopop::GeoGrid< LocationContent >::m_locations, and geopop::GeoGrid< LocationContent >::m_tree.
Referenced by visualization::MapController::MapController().
template<class LocationContent> std::shared_ptr<Location<LocationContent> > geopop::GeoGrid< LocationContent >::GetById (unsigned int id) const inline
Gets a Location by Id and check if the Id exists.
Definition at line 65 of file GeoGrid.h.
Referenced by geopop::GeoGridReader::AddCommutes(), and geopop::CommutesCSVReader::FillGeoGrid().
template<class LocationContent> stride::Population* geopop::GeoGrid< LocationContent >::GetPopulation () const inline
Get the Population associated with this GeoGrid.
Definition at line 68 of file GeoGrid.h.
Referenced by geopop::Generator< ID >::Apply(), and geopop::Populator< ID >::Apply().
template<class LocationContent> vector< const Location< LocationContent > * > geopop::GeoGrid< LocationContent >::LocationsInRadius (const Location< LocationContent > & start, double radius) const
Search for locations in radius (in km) around start.
Definition at line 112 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::CheckFinalized(), and geopop::MakeCollector().
Referenced by geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetNearbyPools(), and geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetPopulation().
template<class LocationContent> template<typename = std::enable_if<std::is_same<LocationContent, Epidemiologic>::value>> std::vector<stride::ContactPool*> geopop::GeoGrid< LocationContent >::GetNearbyPools (stride::ContactType::Id id, const Location< Epidemiologic > & start, double startRadius = 10.0) const inline
Find contactpools in startRadius (in km) around start and, if none are found, double the radius and search again until the radius gets infinite.
May return an empty vector when there are really no pools to be found (empty grid).
Definition at line 77 of file GeoGrid.h.
template<class LocationContent > set< const Location< LocationContent > * > geopop::GeoGrid< LocationContent >::LocationsInBox (double long1, double lat1, double long2, double lat2) const
Gets the locations in a rectangle determined by the two coordinates (long1, lat1) and (long2, lat2).
The coordinates must be positioned on the diagonal, i.e:
p1 --—+ +----—p1 | | | | | | or | | | | | | +----—p2 p2---—+
Definition at line 84 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::CheckFinalized(), and geopop::MakeCollector().
Referenced by geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetNearbyPools(), and geopop::GeoGrid< LocationContent >::LocationsInBox().
template<class LocationContent> set< const Location< LocationContent > * > geopop::GeoGrid< LocationContent >::LocationsInBox (Location< LocationContent > * loc1, Location< LocationContent > * loc2) const
Gets the location in a rectangle defined by the two Locations.
Definition at line 104 of file GeoGrid.cpp.
References geopop::Location< Content >::GetCoordinate(), and geopop::GeoGrid< LocationContent >::LocationsInBox().
template<class LocationContent > vector< Location< LocationContent > * > geopop::GeoGrid< LocationContent >::TopK (size_t k) const
Gets the K biggest (in population count) locations of this GeoGrid.
Definition at line 151 of file GeoGrid.cpp.
References geopop::Location< Content >::GetContent(), and geopop::GeoGrid< LocationContent >::m_locations.
Referenced by geopop::Generator< ID >::Apply(), and geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetNearbyPools().
template<class LocationContent > template<typename Policy , typename F > GeoAggregator< Policy, F > geopop::GeoGrid< LocationContent >::BuildAggregator (F functor, typename Policy::Args && args) const
Build a GeoAggregator with a predefined functor and given args for the Policy.
Definition at line 52 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::m_tree.
Referenced by geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetNearbyPools().
template<class LocationContent > template<typename Policy > GeoAggregator< Policy > geopop::GeoGrid< LocationContent >::BuildAggregator (typename Policy::Args && args) const
Build a GeoAggregator that gets its functor when calling, with given args for the Policy.
Definition at line 59 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::m_tree.
template<class LocationContent> iterator geopop::GeoGrid< LocationContent >::begin () inline
Iterator to first Location.
Definition at line 127 of file GeoGrid.h.
Referenced by visualization::MapController::Initialize(), and visualization::MapController::MapController().
template<class LocationContent> iterator geopop::GeoGrid< LocationContent >::end () inline
Iterator to the end of the Location storage.
Definition at line 130 of file GeoGrid.h.
Referenced by visualization::MapController::Initialize().
template<class LocationContent> const_iterator geopop::GeoGrid< LocationContent >::cbegin () const inline
Const Iterator to first Location.
Definition at line 133 of file GeoGrid.h.
template<class LocationContent> const_iterator geopop::GeoGrid< LocationContent >::cend () const inline
Const iterator to the end of the Location storage.
Definition at line 136 of file GeoGrid.h.
template<class LocationContent> std::shared_ptr<Location<LocationContent> >& geopop::GeoGrid< LocationContent >::operator[] (size_t index) inline
Gets a Location by index, doesn't performs a range check.
Definition at line 139 of file GeoGrid.h.
template<class LocationContent> const std::shared_ptr<Location<LocationContent> >& geopop::GeoGrid< LocationContent >::operator[] (size_t index) const inline
Gets a Location by index, doesn't performs a range check.
Definition at line 142 of file GeoGrid.h.
template<class LocationContent> size_t geopop::GeoGrid< LocationContent >::size () const inline
Gets current size of Location storage.
Definition at line 145 of file GeoGrid.h.
Referenced by geopop::EpiOutputHDF5Writer::Update(), geopop::EpiOutputJSONWriter::Update(), geopop::EpiOutputProtoWriter::Update(), and geopop::GeoGridHDF5Writer::Write().
template<class LocationContent > void geopop::GeoGrid< LocationContent >::CheckFinalized (const std::string & functionName) const private
< Checks whether the GeoGrid is finalized i.e. certain operations can(not) be used.
Definition at line 65 of file GeoGrid.cpp.
References geopop::GeoGrid< LocationContent >::m_finalized.
Referenced by geopop::GeoGrid< LocationContent >::LocationsInBox(), geopop::GeoGrid< LocationContent >::LocationsInRadius(), and geopop::GeoGrid< geopop::geopop::Epidemiologic >::size().
Member Data Documentation
template<class LocationContent> std::vector<std::shared_ptr<Location<LocationContent> > > geopop::GeoGrid< LocationContent >::m_locations private
< Container for Locations in GeoGrid.
Associative container maps Location Id to index in m_locations.
Definition at line 153 of file GeoGrid.h.
Referenced by geopop::GeoGrid< LocationContent >::AddLocation(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::begin(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::cbegin(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::cend(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::end(), geopop::GeoGrid< LocationContent >::Finalize(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetById(), geopop::GeoGrid< geopop::geopop::Epidemiologic >::operator[](), geopop::GeoGrid< geopop::geopop::Epidemiologic >::size(), and geopop::GeoGrid< LocationContent >::TopK().
template<class LocationContent> std::unordered_map<unsigned int, unsigned int> geopop::GeoGrid< LocationContent >::m_id_to_index private
Stores pointer to Popluation, but does not take ownership.
Definition at line 156 of file GeoGrid.h.
Referenced by geopop::GeoGrid< LocationContent >::AddLocation(), and geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetById().
template<class LocationContent> stride::Population* geopop::GeoGrid< LocationContent >::m_population private
Is the GeoGrid finalized (ready for use) yet?
Definition at line 159 of file GeoGrid.h.
Referenced by geopop::GeoGrid< geopop::geopop::Epidemiologic >::GetPopulation().
template<class LocationContent> bool geopop::GeoGrid< LocationContent >::m_finalized private
Internal KdTree for quick spatial lookup.
Definition at line 162 of file GeoGrid.h.
Referenced by geopop::GeoGrid< LocationContent >::AddLocation(), geopop::GeoGrid< LocationContent >::CheckFinalized(), and geopop::GeoGrid< LocationContent >::Finalize().
template<class LocationContent> GeoGridKdTree geopop::GeoGrid< LocationContent >::m_tree private
Definition at line 165 of file GeoGrid.h.
Referenced by geopop::GeoGrid< LocationContent >::BuildAggregator(), and geopop::GeoGrid< LocationContent >::Finalize().
The documentation for this class was generated from the following files:
Generator.h
GeoGrid.h
GeoGrid.cpp