Stride Reference Manual: visualization Namespace Reference
visualization Namespace Reference
Classes
class EpiOutputHDF5Reader
An implementation of the EpiOutputReader using HDF5.
class EpiOutputJSONReader
An implementation of the EpiOutputReader using JSON.
class EpiOutputProtoReader
An implementation of the EpiOutputReader using Protobuf.
class EpiOutputReader
An abstract base class for creating a GeoGrid with the epi-output that was read from a file, can be implemented using multiple file types (proto, hdf5 and json are currently implemented)
class EpiOutputReaderFactory
A Factory for creating the correct implementation of a EpiOutputReader based on the filename extension.
class MapController
MapController for use within the visualization, controller of the GUI and communicates with the qml.
Functions
double distanceOnEarth (double lat1, double long1, double lat2, double long2)
double scaleValue (double low, double high, double value)
QString makePresentablePercentage (double value)
Function Documentation
double visualization::distanceOnEarth (double lat1, double long1, double lat2, double long2)
Definition at line 32 of file MapController.cpp.
Referenced by visualization::MapController::Initialize().
double visualization::scaleValue (double low, double high, double value)
Definition at line 44 of file MapController.cpp.
QString visualization::makePresentablePercentage (double value)
Definition at line 50 of file MapController.cpp.
Referenced by visualization::MapController::SetShownInformation(), and visualization::MapController::UpdateLocations().