Stride Reference Manual: geopop::GeoGridProtoWriter Class Reference
geopop::GeoGridProtoWriter Class Reference
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
#include <GeoGridProtoWriter.h>
Public Member Functions
GeoGridProtoWriter ()=delete
GeoGridProtoWriter cannot be instantiated without stream.
GeoGridProtoWriter (std::shared_ptr< std::ostream > stream)
Construct GeoGridProtoWriter referencing given stream.
void Write (GeoGrid< Epidemiologic > &geoGrid) override
Write the GeoGrid to the ostream in Protobuf format.
Public Member Functions inherited from geopop::GeoGridStreamWriter
GeoGridStreamWriter ()=delete
GeoGridStreamWriter cannot be instantiated without stream.
GeoGridStreamWriter (std::shared_ptr< std::ostream > stream)
Construct GeoGridStreamWriter referencing given stream.
~GeoGridStreamWriter () override=default
Default destructor.
std::shared_ptr< std::ostream > StreamRef ()
Return reference to output stream.
Public Member Functions inherited from geopop::GeoGridWriter
GeoGridWriter ()=default
Default construtor.
virtual ~GeoGridWriter ()=default
Virtual destrutor to make class abstract.
Private Member Functions
void WriteContactPools (stride::ContactType::Id typeId, stride::util::SegmentedVector< stride::ContactPool * > &contactPools, proto::GeoGrid_Location_ContactPools *protoContactPools)
Create a ProtoBuf ContactPools structure.
void WriteContactPool (stride::ContactPool *contactPool, proto::GeoGrid_Location_ContactPools_ContactPool *protoContactPool)
Create a ProtoBuf ContactPool containing all the info needed to reconstruct a ContactPool.
void WriteCoordinate (const Coordinate &coordinate, proto::GeoGrid_Location_Coordinate *protoCoordinate)
Create a ProtoBuf Coordinate containing all the info needed to reconstruct a Coordinate..
void WriteLocation (Location< Epidemiologic > &location, proto::GeoGrid_Location *protoLocation)
Create a ProtoBuf Location containing all the info needed to reconstruct a Location.
void WritePerson (stride::Person *person, proto::GeoGrid_Person *protoPerson)
Create a ProtoBuf Person containing all the info needed to reconstruct a Person.
Private Attributes
std::set< stride::Person * > m_persons_found
The persons found when looping over the ContactPools.
Additional Inherited Members
Protected Attributes inherited from geopop::GeoGridStreamWriter
std::shared_ptr< std::ostream > m_stream
Detailed Description
An implementation of the GeoGridWriter using Protocol Buffers This class is used to write a GeoGrid to a Proto file.
Definition at line 42 of file GeoGridProtoWriter.h.
Constructor & Destructor Documentation
geopop::GeoGridProtoWriter::GeoGridProtoWriter () delete
GeoGridProtoWriter cannot be instantiated without stream.
geopop::GeoGridProtoWriter::GeoGridProtoWriter (std::shared_ptr< std::ostream > stream) explicit
Construct GeoGridProtoWriter referencing given stream.
Member Function Documentation
void geopop::GeoGridProtoWriter::Write (GeoGrid< Epidemiologic > & geoGrid) override virtual
Write the GeoGrid to the ostream in Protobuf format.
Implements geopop::GeoGridStreamWriter.
Definition at line 41 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid::add_locations(), and proto::GeoGrid::add_persons().
void geopop::GeoGridProtoWriter::WriteContactPools (stride::ContactType::Id typeId, stride::util::SegmentedVector< stride::ContactPool * > & contactPools, proto::GeoGrid_Location_ContactPools * protoContactPools) private
Create a ProtoBuf ContactPools structure.
Definition at line 61 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactPools::add_pools(), proto::GeoGrid_Location_ContactPools_Type_College, proto::GeoGrid_Location_ContactPools_Type_Daycare, proto::GeoGrid_Location_ContactPools_Type_Household, proto::GeoGrid_Location_ContactPools_Type_K12School, proto::GeoGrid_Location_ContactPools_Type_PreSchool, proto::GeoGrid_Location_ContactPools_Type_PrimaryCommunity, proto::GeoGrid_Location_ContactPools_Type_SecondaryCommunity, proto::GeoGrid_Location_ContactPools_Type_Workplace, and proto::GeoGrid_Location_ContactPools::set_type().
void geopop::GeoGridProtoWriter::WriteContactPool (stride::ContactPool * contactPool, proto::GeoGrid_Location_ContactPools_ContactPool * protoContactPool) private
Create a ProtoBuf ContactPool containing all the info needed to reconstruct a ContactPool.
Definition at line 80 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_ContactPools_ContactPool::add_people(), stride::ContactPool::GetId(), and proto::GeoGrid_Location_ContactPools_ContactPool::set_id().
void geopop::GeoGridProtoWriter::WriteCoordinate (const Coordinate & coordinate, proto::GeoGrid_Location_Coordinate * protoCoordinate) private
Create a ProtoBuf Coordinate containing all the info needed to reconstruct a Coordinate..
Definition at line 90 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location_Coordinate::set_latitude(), and proto::GeoGrid_Location_Coordinate::set_longitude().
void geopop::GeoGridProtoWriter::WriteLocation (Location< Epidemiologic > & location, proto::GeoGrid_Location * protoLocation) private
Create a ProtoBuf Location containing all the info needed to reconstruct a Location.
Definition at line 97 of file GeoGridProtoWriter.cpp.
References proto::GeoGrid_Location::add_commutes(), proto::GeoGrid_Location::add_contactpools(), geopop::Location< Content >::GetContent(), geopop::Location< Content >::GetCoordinate(), geopop::Location< Content >::GetID(), geopop::Location< Content >::GetName(), geopop::Location< Content >::GetProvince(), stride::ContactType::IdList, proto::GeoGrid_Location::set_allocated_coordinate(), proto::GeoGrid_Location::set_id(), proto::GeoGrid_Location::set_name(), proto::GeoGrid_Location::set_population(), proto::GeoGrid_Location::set_province(), and proto::GeoGrid_Location_Commute::set_to().
void geopop::GeoGridProtoWriter::WritePerson (stride::Person * person, proto::GeoGrid_Person * protoPerson) private
Create a ProtoBuf Person containing all the info needed to reconstruct a Person.
Definition at line 119 of file GeoGridProtoWriter.cpp.
References stride::Person::GetAge(), stride::Person::GetId(), proto::GeoGrid_Person::set_age(), and proto::GeoGrid_Person::set_id().
Member Data Documentation
std::set<stride::Person*> geopop::GeoGridProtoWriter::m_persons_found private
The persons found when looping over the ContactPools.
Definition at line 74 of file GeoGridProtoWriter.h.
The documentation for this class was generated from the following files:
GeoGridProtoWriter.h
GeoGridProtoWriter.cpp