Stride Reference Manual: geopop::Populator< ID > Class Template Reference
geopop::Populator< ID > Class Template Reference
Populator uses geo & pop data to populate ContactPools in the GeoGrid.
#include <Populator.h>
Public Member Functions
Populator (stride::util::RnMan &rnMan, std::shared_ptr< spdlog::logger > logger=nullptr)
Construct with a RnMan and a logger.
~Populator ()=default
Default is OK.
void Apply (GeoGrid< Epidemiologic > &, const GeoGridConfig &)
Populate the ContactPools type ID. This is a placeholder for the specializations.
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &geoGridConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &geoGridConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &ggConfig)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &)
template<>
void Apply (GeoGrid< Epidemiologic > &geoGrid, const GeoGridConfig &geoGridConfig)
Protected Attributes
stride::util::RnMan & m_rn_man
RnManager used by populators.
std::shared_ptr< spdlog::logger > m_logger
Logger used by populators.
Detailed Description
template<typename stride::ContactType::Id ID>
class geopop::Populator< ID >
Populator uses geo & pop data to populate ContactPools in the GeoGrid.
Definition at line 42 of file Populator.h.
Constructor & Destructor Documentation
template<typename stride::ContactType::Id ID> geopop::Populator< ID >::Populator (stride::util::RnMan & rnMan, std::shared_ptr< spdlog::logger > logger = nullptr) inline explicit
Construct with a RnMan and a logger.
Definition at line 46 of file Populator.h.
References stride::util::LogUtils::CreateNullLogger(), geopop::Populator< ID >::m_logger, and geopop::Populator< ID >::~Populator().
template<typename stride::ContactType::Id ID> geopop::Populator< ID >::~Populator () default
Default is OK.
Referenced by geopop::Populator< ID >::Populator().
Member Function Documentation
template<typename stride::ContactType::Id ID> void geopop::Populator< ID >::Apply (GeoGrid< Epidemiologic > & , const GeoGridConfig &) inline
Populate the ContactPools type ID. This is a placeholder for the specializations.
Definition at line 57 of file Populator.h.
template<> void geopop::Populator< stride::ContactType::Id::College >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & geoGridConfig)
Definition at line 33 of file CollegePopulator.cpp.
References AssertThrow, geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::param, and geopop::GeoGridConfig::participation_college.
template<> void geopop::Populator< stride::ContactType::Id::Daycare >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file DaycarePopulator.cpp.
References geopop::GeoGridConfig::param, and geopop::GeoGridConfig::participation_daycare.
template<> void geopop::Populator< stride::ContactType::Id::Household >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & geoGridConfig)
Definition at line 30 of file HouseholdPopulator.cpp.
References geopop::ReferenceHouseHold::ages, stride::Population::CreatePerson(), geopop::GeoGrid< LocationContent >::GetPopulation(), geopop::GeoGridConfig::refHH, and geopop::GeoGridConfig::refHHperHHType.
template<> void geopop::Populator< stride::ContactType::Id::K12School >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig &)
Definition at line 31 of file K12SchoolPopulator.cpp.
template<> void geopop::Populator< stride::ContactType::Id::Daycare >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::PreSchool >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::K12School >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::College >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::Workplace >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::Household >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
template<> void geopop::Populator< stride::ContactType::Id::PreSchool >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & ggConfig)
Definition at line 31 of file PreSchoolPopulator.cpp.
References geopop::GeoGridConfig::param, and geopop::GeoGridConfig::participation_preschool.
template<> void geopop::Populator< stride::ContactType::Id::PrimaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig &)
Definition at line 29 of file PrimaryCommunityPopulator.cpp.
template<> void geopop::Populator< stride::ContactType::Id::SecondaryCommunity >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig &)
Definition at line 32 of file SecondaryCommunityPopulator.cpp.
template<> void geopop::Populator< stride::ContactType::Id::Workplace >::Apply (GeoGrid< Epidemiologic > & geoGrid, const GeoGridConfig & geoGridConfig)
Definition at line 36 of file WorkplacePopulator.cpp.
References AssertThrow, geopop::GeoGridConfig::fraction_college_commuters, geopop::GeoGridConfig::fraction_workplace_commuters, stride::AgeBrackets::Workplace::HasAge(), geopop::GeoGridConfig::info, geopop::GeoGridConfig::param, geopop::GeoGridConfig::participation_workplace, geopop::PopulationInfo::popcount_college, geopop::PopulationInfo::popcount_workplace, and geopop::GeoGridConfig::work_distribution.
Member Data Documentation
template<typename stride::ContactType::Id ID> stride::util::RnMan& geopop::Populator< ID >::m_rn_man protected
RnManager used by populators.
Definition at line 57 of file Populator.h.
template<typename stride::ContactType::Id ID> std::shared_ptr<spdlog::logger> geopop::Populator< ID >::m_logger protected
Logger used by populators.
Definition at line 61 of file Populator.h.
Referenced by geopop::Populator< ID >::Populator().
The documentation for this class was generated from the following file:
Populator.h