Stride Reference Manual: stride::viewers::EpiOutputViewer Class Reference
stride::viewers::EpiOutputViewer Class Reference
Viewer gathers infection count at each sim step.
#include <EpiOutputViewer.h>
Public Member Functions
EpiOutputViewer (std::shared_ptr< SimRunner > runner, unsigned int stride, std::shared_ptr< geopop::EpiOutputWriter > &epi_output_writer)
Instantiate cases viewer.
void Update (sim_event::Id id)
Let viewer perform update.
Private Attributes
std::shared_ptr< SimRunner > m_runner
unsigned int m_stride
unsigned int m_current_step
std::shared_ptr< geopop::EpiOutputWriter > m_epi_output_writer
Detailed Description
Viewer gathers infection count at each sim step.
Definition at line 37 of file EpiOutputViewer.h.
Constructor & Destructor Documentation
stride::viewers::EpiOutputViewer::EpiOutputViewer (std::shared_ptr< SimRunner > runner, unsigned int stride, std::shared_ptr< geopop::EpiOutputWriter > & epi_output_writer) inline explicit
Instantiate cases viewer.
Definition at line 41 of file EpiOutputViewer.h.
References Update().
Member Function Documentation
void stride::viewers::EpiOutputViewer::Update (sim_event::Id id)
Let viewer perform update.
Definition at line 34 of file EpiOutputViewer.cpp.
Referenced by EpiOutputViewer(), and stride::ControlHelper::RegisterViewers().
Member Data Documentation
std::shared_ptr<SimRunner> stride::viewers::EpiOutputViewer::m_runner private
Definition at line 48 of file EpiOutputViewer.h.
unsigned int stride::viewers::EpiOutputViewer::m_stride private
Definition at line 49 of file EpiOutputViewer.h.
unsigned int stride::viewers::EpiOutputViewer::m_current_step private
Definition at line 50 of file EpiOutputViewer.h.
std::shared_ptr<geopop::EpiOutputWriter> stride::viewers::EpiOutputViewer::m_epi_output_writer private
Definition at line 51 of file EpiOutputViewer.h.
The documentation for this class was generated from the following files:
EpiOutputViewer.h
EpiOutputViewer.cpp