Stride Reference Manual: geopop::Location< Content > Class Template Reference
geopop::Location< Content > Class Template Reference
Location for use within the GeoGrid, contains Coordinate and meta data of that coordinate.
#include <Epidemiologic.h>
Public Member Functions
Location (unsigned int id, unsigned int province, std::shared_ptr< Content > content, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="")
Parametrized constructor with population count.
template<typename = std::enable_if<std::is_same<Content, Epidemiologic>::value>>
Location (unsigned int id, unsigned int province, Coordinate coordinate=Coordinate(0.0, 0.0), std::string name="", unsigned int popCount=0U, unsigned int householdType=0U, double youngOldFraction=1.0)
Specialised contructor for Epidemiologic as template.
bool operator== (const Location< Content > &other) const
Perform a full comparison with the other location.
const Coordinate GetCoordinate () const
Gets the Coordinate of this Location.
unsigned int GetID () const
Gets ID of this Location.
std::string GetName () const
Gets the name.
unsigned int GetProvince () const
Gets the province.
void SetCoordinate (const Coordinate &coordinate)
Sets the Coordinate of this Location.
std::shared_ptr< Content > GetContent () const
Gets the content.
template<unsigned int T>
double get () const
Get the latitude or longitude from the coordinate of the location.
Private Attributes
std::shared_ptr< Content > m_content
Content of the Location.
Coordinate m_coordinate
Coordinate of the Location.
unsigned int m_id = 0U
Id.
std::string m_name
Name.
unsigned int m_province
Province id.
Detailed Description
template<class Content>
class geopop::Location< Content >
Location for use within the GeoGrid, contains Coordinate and meta data of that coordinate.
Definition at line 39 of file Epidemiologic.h.
Constructor & Destructor Documentation
template<class Content> geopop::Location< Content >::Location (unsigned int id, unsigned int province, std::shared_ptr< Content > content, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "")
Parametrized constructor with population count.
Definition at line 30 of file Location.cpp.
template<class Content> template<typename = std::enable_if<std::is_same<Content, Epidemiologic>::value>> geopop::Location< Content >::Location (unsigned int id, unsigned int province, Coordinate coordinate = Coordinate(0.0, 0.0), std::string name = "", unsigned int popCount = 0U, unsigned int householdType = 0U, double youngOldFraction = 1.0) inline
Specialised contructor for Epidemiologic as template.
Definition at line 52 of file Location.h.
Member Function Documentation
template<class Content> bool geopop::Location< Content >::operator== (const Location< Content > & other) const
Perform a full comparison with the other location.
Definition at line 36 of file Location.cpp.
References geopop::Location< Content >::get(), geopop::Location< Content >::GetContent(), geopop::Location< Content >::GetID(), geopop::Location< Content >::GetName(), geopop::Location< Content >::GetProvince(), and geopop::Location< Content >::m_content.
Referenced by geopop::Location< geopop::Epidemiologic >::Location().
template<class Content> const Coordinate geopop::Location< Content >::GetCoordinate () const inline
Gets the Coordinate of this Location.
Definition at line 62 of file Location.h.
Referenced by geopop::GeoGrid< LocationContent >::LocationsInBox(), geopop::GeoGridHDF5Writer::WriteLocation(), geopop::GeoGridJSONWriter::WriteLocation(), and geopop::GeoGridProtoWriter::WriteLocation().
template<class Content> unsigned int geopop::Location< Content >::GetID () const inline
Gets ID of this Location.
Definition at line 65 of file Location.h.
Referenced by geopop::Location< Content >::operator==(), geopop::GeoGridHDF5Writer::WriteLocation(), geopop::GeoGridJSONWriter::WriteLocation(), and geopop::GeoGridProtoWriter::WriteLocation().
template<class Content> std::string geopop::Location< Content >::GetName () const inline
Gets the name.
Definition at line 68 of file Location.h.
Referenced by geopop::Location< Content >::operator==(), geopop::GeoGridHDF5Writer::WriteLocation(), geopop::GeoGridJSONWriter::WriteLocation(), and geopop::GeoGridProtoWriter::WriteLocation().
template<class Content> unsigned int geopop::Location< Content >::GetProvince () const inline
Gets the province.
Definition at line 71 of file Location.h.
Referenced by geopop::Location< Content >::operator==(), geopop::GeoGridHDF5Writer::WriteLocation(), geopop::GeoGridJSONWriter::WriteLocation(), and geopop::GeoGridProtoWriter::WriteLocation().
template<class Content> void geopop::Location< Content >::SetCoordinate (const Coordinate & coordinate) inline
Sets the Coordinate of this Location.
Definition at line 74 of file Location.h.
template<class Content> std::shared_ptr<Content> geopop::Location< Content >::GetContent () const inline
Gets the content.
Definition at line 77 of file Location.h.
Referenced by geopop::Generator< ID >::AddPools(), geopop::Location< Content >::operator==(), geopop::GeoGrid< LocationContent >::TopK(), geopop::GeoGridHDF5Writer::WriteLocation(), geopop::GeoGridJSONWriter::WriteLocation(), and geopop::GeoGridProtoWriter::WriteLocation().
template<class Content> template<unsigned int T> double geopop::Location< Content >::get () const inline
Get the latitude or longitude from the coordinate of the location.
Definition at line 81 of file Location.h.
Referenced by geopop::Location< Content >::operator==().
Member Data Documentation
template<class Content> std::shared_ptr<Content> geopop::Location< Content >::m_content private
Content of the Location.
Definition at line 90 of file Location.h.
Referenced by geopop::Location< geopop::Epidemiologic >::GetContent(), and geopop::Location< Content >::operator==().
template<class Content> Coordinate geopop::Location< Content >::m_coordinate private
Coordinate of the Location.
Definition at line 91 of file Location.h.
Referenced by geopop::Location< geopop::Epidemiologic >::get(), geopop::Location< geopop::Epidemiologic >::GetCoordinate(), and geopop::Location< geopop::Epidemiologic >::SetCoordinate().
template<class Content> unsigned int geopop::Location< Content >::m_id = 0U private
Id.
Definition at line 92 of file Location.h.
Referenced by geopop::Location< geopop::Epidemiologic >::GetID().
template<class Content> std::string geopop::Location< Content >::m_name private
Name.
Definition at line 93 of file Location.h.
Referenced by geopop::Location< geopop::Epidemiologic >::GetName().
template<class Content> unsigned int geopop::Location< Content >::m_province private
Province id.
Definition at line 94 of file Location.h.
Referenced by geopop::Location< geopop::Epidemiologic >::GetProvince().
The documentation for this class was generated from the following files:
Epidemiologic.h
Location.h
Location.cpp