Stride Reference Manual: H5Utils Namespace Reference
H5Utils Namespace Reference
Classes
struct H5Commute
struct H5EpiOutput
struct H5Person
struct H5PoolPerson
Functions
template<>
CompType GetCompoundType< H5Commute > ()
template<>
CompType GetCompoundType< H5PoolPerson > ()
template<>
CompType GetCompoundType< H5Person > ()
template<>
CompType GetCompoundType< H5EpiOutput > ()
DataSpace CreateSpace (hsize_t size)
H5::PredType HDF5Type (const int &)
H5::PredType HDF5Type (const unsigned int &)
H5::PredType HDF5Type (const long &)
H5::PredType HDF5Type (const unsigned long &)
H5::PredType HDF5Type (const float &)
H5::PredType HDF5Type (const double &)
H5::StrType HDF5Type (const string &value)
template<typename T >
H5::CompType GetCompoundType ()
template<typename T >
void WriteAttribute (const T &value, const std::string &name, H5::H5Object &h5Object)
template<>
void WriteAttribute (const std::string &value, const std::string &name, H5::H5Object &h5Object)
template<typename T >
void ReadAttribute (T &value, const std::string &name, const H5::H5Object &h5Object)
template<>
void ReadAttribute (std::string &value, const std::string &name, const H5::H5Object &h5Object)
Function Documentation
template<> CompType H5Utils::GetCompoundType< H5Commute > ()
Definition at line 24 of file H5Utils.cpp.
Referenced by geopop::GeoGridHDF5Reader::ReadLocation(), and geopop::GeoGridHDF5Writer::WriteCommutes().
template<> CompType H5Utils::GetCompoundType< H5PoolPerson > ()
Definition at line 33 of file H5Utils.cpp.
Referenced by geopop::GeoGridHDF5Reader::ReadContactPool(), and geopop::GeoGridHDF5Writer::WriteContactPool().
template<> CompType H5Utils::GetCompoundType< H5Person > ()
Definition at line 41 of file H5Utils.cpp.
Referenced by geopop::GeoGridHDF5Reader::ReadPeople(), and geopop::GeoGridHDF5Writer::WritePeople().
template<> CompType H5Utils::GetCompoundType< H5EpiOutput > ()
Definition at line 58 of file H5Utils.cpp.
Referenced by visualization::EpiOutputHDF5Reader::ReadDay(), and geopop::EpiOutputHDF5Writer::Update().
H5::DataSpace H5Utils::CreateSpace (hsize_t size)
Definition at line 67 of file H5Utils.cpp.
Referenced by geopop::EpiOutputHDF5Writer::Update(), WriteAttribute(), geopop::GeoGridHDF5Writer::WriteCommutes(), geopop::GeoGridHDF5Writer::WriteContactPool(), and geopop::GeoGridHDF5Writer::WritePeople().
H5::PredType H5Utils::HDF5Type (const int &)
Definition at line 73 of file H5Utils.cpp.
Referenced by WriteAttribute().
H5::PredType H5Utils::HDF5Type (const unsigned int &)
Definition at line 75 of file H5Utils.cpp.
H5::PredType H5Utils::HDF5Type (const long &)
Definition at line 77 of file H5Utils.cpp.
H5::PredType H5Utils::HDF5Type (const unsigned long &)
Definition at line 79 of file H5Utils.cpp.
H5::PredType H5Utils::HDF5Type (const float &)
Definition at line 81 of file H5Utils.cpp.
H5::PredType H5Utils::HDF5Type (const double &)
Definition at line 83 of file H5Utils.cpp.
H5::StrType H5Utils::HDF5Type (const string & value)
Definition at line 85 of file H5Utils.cpp.
template<typename T > H5::CompType H5Utils::GetCompoundType ()
template<typename T > void H5Utils::WriteAttribute (const T & value, const std::string & name, H5::H5Object & h5Object) inline
Definition at line 74 of file H5Utils.h.
References CreateSpace(), and HDF5Type().
Referenced by geopop::EpiOutputHDF5Writer::Update(), geopop::EpiOutputHDF5Writer::Write(), geopop::GeoGridHDF5Writer::Write(), geopop::GeoGridHDF5Writer::WriteCommutes(), geopop::GeoGridHDF5Writer::WriteContactPool(), geopop::GeoGridHDF5Writer::WriteLocation(), and geopop::GeoGridHDF5Writer::WritePeople().
template<> void H5Utils::WriteAttribute (const std::string & value, const std::string & name, H5::H5Object & h5Object) inline
Definition at line 81 of file H5Utils.h.
References CreateSpace(), and HDF5Type().
template<typename T > void H5Utils::ReadAttribute (T & value, const std::string & name, const H5::H5Object & h5Object) inline
Definition at line 88 of file H5Utils.h.
Referenced by visualization::EpiOutputHDF5Reader::Read(), geopop::GeoGridHDF5Reader::ReadContactPool(), visualization::EpiOutputHDF5Reader::ReadDay(), geopop::GeoGridHDF5Reader::ReadLocation(), geopop::GeoGridHDF5Reader::ReadLocations(), and geopop::GeoGridHDF5Reader::ReadPeople().
template<> void H5Utils::ReadAttribute (std::string & value, const std::string & name, const H5::H5Object & h5Object) inline
Definition at line 96 of file H5Utils.h.