Stride Reference Manual: geopop::GeoGridJSONReader Class Reference
geopop::GeoGridJSONReader Class Reference
An implementation of the GeoGridReader using JSON.
#include <GeoGridJSONReader.h>
Public Member Functions
GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
GeoGridJSONReader (const GeoGridJSONReader &)=delete
No copy constructor.
GeoGridJSONReader operator= (const GeoGridJSONReader &)=delete
No copy assignement.
void Read () override
Actually perform the read and return the GeoGrid.
template<>
string ParseValue (const json &value) const
Public Member Functions inherited from geopop::GeoGridStreamReader
GeoGridStreamReader (std::unique_ptr< std::istream > inputStream, stride::Population *pop)
Parametrized constructor.
GeoGridStreamReader (const GeoGridStreamReader &)=delete
No copy constructor.
GeoGridStreamReader & operator= (const GeoGridStreamReader &)=delete
No copy assignment.
~GeoGridStreamReader () override=default
Default destructor.
Public Member Functions inherited from geopop::GeoGridReader
GeoGridReader (stride::Population *pop)
Parametrized constructor.
GeoGridReader (const GeoGridReader &)=delete
No copy constructor.
GeoGridReader & operator= (const GeoGridReader &)=delete
No copy assignment.
virtual ~GeoGridReader ()=default
Default destructor.
Private Member Functions
stride::Person * ParsePerson (const nlohmann::json &person)
Create a Person based on the information stored in the provided JSON.
std::shared_ptr< Location< Epidemiologic > > ParseLocation (const nlohmann::json &location)
Create a Location based on the information stored in the provided JSON.
Coordinate ParseCoordinate (const nlohmann::json &coordinate)
Create a Coordinate based on the information stored in the provided JSON.
void ParseContactPool (const std::shared_ptr< Location< Epidemiologic >> &location, const nlohmann::json &contactPool, stride::ContactType::Id type)
Create a ContactPool based on the information stored in the provided JSON.
template<typename T >
T ParseValue (const nlohmann::json &value) const
Parse value of type T.
Additional Inherited Members
Protected Member Functions inherited from geopop::GeoGridReader
void AddCommutes (GeoGrid< Epidemiologic > &geoGrid)
Add the commutes that were found to their respective Locations symmetrically.
Protected Attributes inherited from geopop::GeoGridStreamReader
std::unique_ptr< std::istream > m_inputStream
File to read.
Protected Attributes inherited from geopop::GeoGridReader
std::map< unsigned int, stride::Person * > m_people
< Store the persons (id->person) that were found while loping over the ContactPools.
std::vector< std::tuple< unsigned int, unsigned int, double > > m_commutes
stride::Population * m_population
Population to use in the GeoGrid may be nullptr.
Detailed Description
An implementation of the GeoGridReader using JSON.
This class is used to read a GeoGrid from a JSON file.
Definition at line 34 of file GeoGridJSONReader.h.
Constructor & Destructor Documentation
geopop::GeoGridJSONReader::GeoGridJSONReader (std::unique_ptr< std::istream > inputStream, stride::Population * pop)
Construct the GeoGridJSONReader with the istream which contains the JSON.
Definition at line 32 of file GeoGridJSONReader.cpp.
geopop::GeoGridJSONReader::GeoGridJSONReader (const GeoGridJSONReader &) delete
No copy constructor.
Member Function Documentation
GeoGridJSONReader geopop::GeoGridJSONReader::operator= (const GeoGridJSONReader &) delete
No copy assignement.
void geopop::GeoGridJSONReader::Read () override virtual
Actually perform the read and return the GeoGrid.
Implements geopop::GeoGridStreamReader.
Definition at line 37 of file GeoGridJSONReader.cpp.
References geopop::GeoGridReader::AddCommutes(), geopop::GeoGridReader::m_commutes, geopop::GeoGridStreamReader::m_inputStream, geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, ParseLocation(), ParsePerson(), and stride::Population::RefGeoGrid().
stride::Person * geopop::GeoGridJSONReader::ParsePerson (const nlohmann::json & person) private
Create a Person based on the information stored in the provided JSON.
Definition at line 85 of file GeoGridJSONReader.cpp.
References stride::Population::CreatePerson(), and geopop::GeoGridReader::m_population.
Referenced by Read().
std::shared_ptr< Location< Epidemiologic > > geopop::GeoGridJSONReader::ParseLocation (const nlohmann::json & location) private
Create a Location based on the information stored in the provided JSON.
Definition at line 101 of file GeoGridJSONReader.cpp.
References geopop::GeoGridReader::m_commutes, ParseContactPool(), and ParseCoordinate().
Referenced by Read().
Coordinate geopop::GeoGridJSONReader::ParseCoordinate (const nlohmann::json & coordinate) private
Create a Coordinate based on the information stored in the provided JSON.
Definition at line 145 of file GeoGridJSONReader.cpp.
Referenced by ParseLocation().
void geopop::GeoGridJSONReader::ParseContactPool (const std::shared_ptr< Location< Epidemiologic >> & location, const nlohmann::json & contactPool, stride::ContactType::Id type) private
Create a ContactPool based on the information stored in the provided JSON.
Definition at line 152 of file GeoGridJSONReader.cpp.
References stride::ContactPoolSys::CreateContactPool(), geopop::GeoGridReader::m_people, geopop::GeoGridReader::m_population, and stride::Population::RefPoolSys().
Referenced by ParseLocation().
template<typename T > T geopop::GeoGridJSONReader::ParseValue (const nlohmann::json & value) const private
Parse value of type T.
Definition at line 71 of file GeoGridJSONReader.cpp.
template<> string geopop::GeoGridJSONReader::ParseValue (const json & value) const
Definition at line 80 of file GeoGridJSONReader.cpp.
The documentation for this class was generated from the following files:
GeoGridJSONReader.h
GeoGridJSONReader.cpp